/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account */
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and receive tokens */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token and issue new token pair */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the refresh token */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects owned by the authenticated user */
        get: operations["listProjects"];
        put?: never;
        /** Create a new project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** Get a single project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Delete a project */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Update project title or description */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{projectId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** Get project stats */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectStats"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/acts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** List all acts in a project */
        get: operations["listActs"];
        put?: never;
        /** Create a new act */
        post: operations["createAct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/acts/{actId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                actId: string;
            };
            cookie?: never;
        };
        /** Get a single act */
        get: operations["getAct"];
        put?: never;
        post?: never;
        /** Delete an act and all its chapters and scenes */
        delete: operations["deleteAct"];
        options?: never;
        head?: never;
        /** Update an act */
        patch: operations["updateAct"];
        trace?: never;
    };
    "/projects/{projectId}/acts/{actId}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                actId: string;
            };
            cookie?: never;
        };
        /** List all chapters in an act */
        get: operations["listChapters"];
        put?: never;
        /** Create a new chapter in an act */
        post: operations["createChapter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/acts/{actId}/chapters/{chapterId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                actId: string;
                chapterId: string;
            };
            cookie?: never;
        };
        /** Get a single chapter */
        get: operations["getChapter"];
        put?: never;
        post?: never;
        /** Delete a chapter and all its scenes */
        delete: operations["deleteChapter"];
        options?: never;
        head?: never;
        /** Update a chapter */
        patch: operations["updateChapter"];
        trace?: never;
    };
    "/chapters/{chapterId}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: string;
            };
            cookie?: never;
        };
        /** List all scenes in a chapter */
        get: operations["listScenes"];
        put?: never;
        /** Create a new scene */
        post: operations["createScene"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chapters/{chapterId}/scenes/{sceneId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: string;
                sceneId: string;
            };
            cookie?: never;
        };
        /** Get a single scene */
        get: operations["getScene"];
        put?: never;
        post?: never;
        /** Delete a scene */
        delete: operations["deleteScene"];
        options?: never;
        head?: never;
        /** Update a scene (partial — send only changed fields) */
        patch: operations["updateScene"];
        trace?: never;
    };
    "/projects/{projectId}/git/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** Current timeline and most recent Chronicle */
        get: operations["gitStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/git/chronicle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot all scene content and create a commit (Chronicle) on the current Timeline. Returns 201 with the entry on success, or 200 with a "nothing to chronicle" message when nothing changed. */
        post: operations["chronicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/git/lore": {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** Paginated Chronicle history (git log) for the current Timeline */
        get: operations["lore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/git/echo": {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** Unified diff between two Chronicle SHAs */
        get: operations["echo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/git/timelines": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** List all Timelines (branches) in the project */
        get: operations["listTimelines"];
        put?: never;
        /** Create a new Timeline (branch) and switch to it */
        post: operations["diverge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/git/timelines/{timelineName}/travel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                timelineName: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch the active Timeline (checkout branch) */
        post: operations["travelTo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/git/timelines/{timelineName}/canonize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                timelineName: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fast-forward merge a Timeline into Canon. Returns 200 on success or 409 if the histories have diverged (a Paradox). */
        post: operations["canonize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/wiki/entities": {
        parameters: {
            query?: {
                /** @description Filter by entity type. */
                type?: components["schemas"]["EntityType"];
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** List wiki entities, optionally filtered by type */
        get: operations["listEntities"];
        put?: never;
        /** Create a new wiki entity */
        post: operations["createEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/wiki/entities/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                entityId: string;
            };
            cookie?: never;
        };
        /** Get a single wiki entity */
        get: operations["getEntity"];
        put?: never;
        post?: never;
        /** Delete a wiki entity */
        delete: operations["deleteEntity"];
        options?: never;
        head?: never;
        /** Update a wiki entity */
        patch: operations["updateEntity"];
        trace?: never;
    };
    "/projects/{projectId}/wiki/entities/{entityId}/children": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                entityId: string;
            };
            cookie?: never;
        };
        /** List child entities of a parent entity */
        get: operations["listChildEntities"];
        put?: never;
        /** Create a child entity under a parent */
        post: operations["createChildEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/wiki/entities/{entityId}/image": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                entityId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload or replace an entity portrait image */
        post: operations["uploadEntityImage"];
        /** Remove an entity's portrait image */
        delete: operations["deleteEntityImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/wiki/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** List all entity relationships in the project */
        get: operations["listRelationships"];
        put?: never;
        /** Create a relationship between two entities */
        post: operations["createRelationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/wiki/relationships/{relationshipId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                relationshipId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a relationship */
        delete: operations["deleteRelationship"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/wiki/graph": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** Get all entities and relationships in one call (for graph rendering) */
        get: operations["getWikiGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/wiki/magic-rules": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** List all magic / world-system rules */
        get: operations["listMagicRules"];
        put?: never;
        /** Create a new magic rule */
        post: operations["createMagicRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/wiki/magic-rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ruleId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a magic rule */
        delete: operations["deleteMagicRule"];
        options?: never;
        head?: never;
        /** Update a magic rule */
        patch: operations["updateMagicRule"];
        trace?: never;
    };
    "/projects/{projectId}/wiki/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** List all timeline events with resolved dates. Anchored events have their year/month/day computed from their anchor chain. */
        get: operations["listTimelineEvents"];
        put?: never;
        /** Create a new timeline event */
        post: operations["createTimelineEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/wiki/timeline/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                eventId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a timeline event */
        delete: operations["deleteTimelineEvent"];
        options?: never;
        head?: never;
        /** Update a timeline event */
        patch: operations["updateTimelineEvent"];
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        /** Delete account and all owned data */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stored key hints for the authenticated user */
        get: operations["listAPIKeys"];
        put?: never;
        /** Store or replace an encrypted API key for a provider */
        post: operations["upsertAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/api-keys/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove the stored key for a provider */
        delete: operations["deleteAPIKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novel-structures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the full catalog of seeded story structure templates (no auth required) */
        get: operations["listNovelStructures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/guide/structure/score": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score answers against the structure matrix and return ranked suggestions (no persistence) */
        post: operations["scoreStructure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** Get the current story structure selection for a project */
        get: operations["getProjectStructure"];
        /** Set or clear the story structure selection for a project */
        put: operations["updateProjectStructure"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/wiki/autolink": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        /** Find entity name mentions in a block of text */
        get: operations["autolink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            message?: string;
            detail?: string;
        };
        MessageResponse: {
            message: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            display_name: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        LogoutRequest: {
            refresh_token: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @enum {string} */
            role: "reader" | "writer" | "editor" | "admin";
            /** Format: date-time */
            created_at: string;
        };
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            tokens: components["schemas"]["TokenPair"];
        };
        CreateProjectRequest: {
            title: string;
            description?: string;
            genres?: string[];
        };
        UpdateProjectRequest: {
            title?: string;
            description?: string;
        };
        ProjectResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            title: string;
            description: string;
            genres: string[];
            archived: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectStats: {
            scene_count: number;
            chapter_count: number;
            total_word_count: number;
            /** Format: date-time */
            last_updated_at: string;
        };
        CreateActRequest: {
            title: string;
            summary?: string;
            sort_order?: number;
        };
        UpdateActRequest: {
            title?: string;
            summary?: string;
            sort_order?: number;
        };
        ActResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            title: string;
            summary: string;
            sort_order: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateChapterRequest: {
            title: string;
            summary?: string;
            sort_order?: number;
        };
        UpdateChapterRequest: {
            title?: string;
            summary?: string;
            sort_order?: number;
        };
        ChapterResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            act_id: string;
            title: string;
            summary: string;
            sort_order: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateSceneRequest: {
            title: string;
            content?: string;
            pov?: string;
            tense?: string;
            tags?: string[];
            summary?: string;
            sort_order?: number;
        };
        UpdateSceneRequest: {
            title?: string;
            content?: string;
            pov?: string;
            tense?: string;
            tags?: string[];
            summary?: string;
            summary_stale?: boolean;
            sort_order?: number;
        };
        SceneResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            chapter_id: string;
            title: string;
            content: string;
            pov?: string;
            tense?: string;
            tags?: string[];
            summary?: string;
            summary_stale?: boolean;
            sort_order: number;
            /** @description Server-computed word count; updated on every content save. */
            word_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UpsertAPIKeyRequest: {
            /** @description e.g. openai, anthropic, gemini, mistral, custom */
            provider: string;
            /** @description Raw API key — encrypted at rest, never returned. */
            key: string;
        };
        APIKeyResponse: {
            /** Format: uuid */
            id: string;
            provider: string;
            /** @description Last 4 characters of the key for display only. */
            key_hint: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ChronicleRequest: {
            note: string;
        };
        ChronicleEntry: {
            sha: string;
            short_sha: string;
            note: string;
            author: string;
            /** Format: date-time */
            created_at: string;
        };
        NothingToChronicle: {
            /** @example nothing to chronicle */
            message: string;
            last_chronicle?: components["schemas"]["ChronicleEntry"];
        };
        TimelineInfo: {
            name: string;
            is_canon: boolean;
            is_active: boolean;
            head_sha: string;
            /** Format: date-time */
            created_at: string;
        };
        GitStatusResponse: {
            current_timeline: string;
            last_chronicle?: components["schemas"]["ChronicleEntry"];
        };
        EchoResponse: {
            from_sha: string;
            to_sha: string;
            diff: string;
        };
        DivergeRequest: {
            timeline_name: string;
            /** @description Pin the diverge to a specific Chronicle; defaults to HEAD. */
            from_sha?: string;
        };
        CanonizeResult: {
            merged_sha?: string;
            has_paradox: boolean;
            paradox_note?: string;
        };
        /** @enum {string} */
        EntityType: "character" | "location" | "faction" | "item" | "concept" | "lore";
        CreateEntityRequest: {
            type: components["schemas"]["EntityType"];
            name: string;
            summary?: string;
            attributes?: {
                [key: string]: string;
            };
            /** Format: uuid */
            parent_entity_id?: string;
        };
        UpdateEntityRequest: {
            name?: string;
            summary?: string;
            attributes?: {
                [key: string]: string;
            };
        };
        EntityResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            parent_entity_id?: string | null;
            type: components["schemas"]["EntityType"];
            name: string;
            summary: string;
            attributes: {
                [key: string]: string;
            };
            /** @description Presigned MinIO URL valid for ~4 hours; absent when no image is stored. */
            image_url?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateRelationshipRequest: {
            /** Format: uuid */
            from_entity_id: string;
            /** Format: uuid */
            to_entity_id: string;
            /** @description e.g. 'allied_with', 'enemy_of', 'parent_of' */
            type: string;
            description?: string;
        };
        RelationshipResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            from_entity_id: string;
            /** Format: uuid */
            to_entity_id: string;
            type: string;
            description?: string;
            /** Format: date-time */
            created_at: string;
        };
        WikiGraphResponse: {
            entities: components["schemas"]["EntityResponse"][];
            relationships: components["schemas"]["RelationshipResponse"][];
        };
        CreateMagicRuleRequest: {
            name: string;
            description?: string;
        };
        UpdateMagicRuleRequest: {
            name?: string;
            description?: string;
        };
        MagicRuleResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            name: string;
            description: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateTimelineEventRequest: {
            name: string;
            description?: string;
            /**
             * Format: uuid
             * @description Optional entity this event is anchored to.
             */
            entity_id?: string;
            era?: string;
            year?: number | null;
            month?: number | null;
            day?: number | null;
            /**
             * Format: uuid
             * @description Mutually exclusive with year/month/day.
             */
            anchor_event_id?: string | null;
            anchor_offset_year?: number | null;
            anchor_offset_month?: number | null;
            anchor_offset_day?: number | null;
        };
        UpdateTimelineEventRequest: {
            name?: string;
            description?: string;
            era?: string;
            year?: number | null;
            month?: number | null;
            day?: number | null;
        };
        TimelineEventResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            entity_id?: string | null;
            name: string;
            description: string;
            era: string;
            year?: number | null;
            month?: number | null;
            day?: number | null;
            /** Format: uuid */
            anchor_event_id?: string | null;
            anchor_offset_year?: number | null;
            anchor_offset_month?: number | null;
            anchor_offset_day?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AutolinkRequest: {
            text: string;
        };
        AutolinkMatch: {
            /** Format: uuid */
            entity_id: string;
            entity_name: string;
            start: number;
            end: number;
        };
        StructurePhase: {
            name: string;
            description: string;
            hints: string;
        };
        NovelStructureResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            phases: components["schemas"]["StructurePhase"][];
            strengths: string;
            risks: string;
        };
        StructureScoreRequest: {
            answers: {
                [key: string]: string[];
            };
        };
        StructureScoreEntry: {
            /** Format: uuid */
            structure_id: string;
            name: string;
            score: number;
            is_secondary: boolean;
        };
        StructureScoreResponse: {
            ranked: components["schemas"]["StructureScoreEntry"][];
        };
        ProjectStructureResponse: {
            /** Format: uuid */
            structure_id?: string | null;
            structure_name?: string | null;
            phases?: components["schemas"]["StructurePhase"][] | null;
            structure_custom?: Record<string, never> | null;
        };
        UpdateProjectStructureRequest: {
            /** Format: uuid */
            structure_id?: string | null;
            structure_custom?: Record<string, never> | null;
        };
    };
    responses: {
        /** @description Missing or invalid JWT. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Validation or binding error. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New token pair issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Logged out. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Updated project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listActs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of acts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createAct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActRequest"];
            };
        };
        responses: {
            /** @description Act created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                actId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Act details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteAct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                actId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Act deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                actId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActRequest"];
            };
        };
        responses: {
            /** @description Updated act. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listChapters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                actId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of chapters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                actId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChapterRequest"];
            };
        };
        responses: {
            /** @description Chapter created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                actId: string;
                chapterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                actId: string;
                chapterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                actId: string;
                chapterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChapterRequest"];
            };
        };
        responses: {
            /** @description Updated chapter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listScenes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of scenes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createScene: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSceneRequest"];
            };
        };
        responses: {
            /** @description Scene created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getScene: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: string;
                sceneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scene details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteScene: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: string;
                sceneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scene deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateScene: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapterId: string;
                sceneId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSceneRequest"];
            };
        };
        responses: {
            /** @description Updated scene. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    gitStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Git status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitStatusResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    chronicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChronicleRequest"];
            };
        };
        responses: {
            /** @description Nothing to chronicle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NothingToChronicle"];
                };
            };
            /** @description Chronicle created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChronicleEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    lore: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chronicle entries, most recent first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChronicleEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    echo: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Diff between the two SHAs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EchoResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTimelines: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of timelines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineInfo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    diverge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DivergeRequest"];
            };
        };
        responses: {
            /** @description New timeline created; returns full list of timelines. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineInfo"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    travelTo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                timelineName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Now on the requested timeline; returns updated status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitStatusResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    canonize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                timelineName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline merged into Canon. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonizeResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Paradox — histories have diverged; manual resolution required. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonizeResult"];
                };
            };
        };
    };
    listEntities: {
        parameters: {
            query?: {
                /** @description Filter by entity type. */
                type?: components["schemas"]["EntityType"];
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of entities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createEntity: {
        parameters: {
            query?: {
                /** @description Filter by entity type. */
                type?: components["schemas"]["EntityType"];
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntityRequest"];
            };
        };
        responses: {
            /** @description Entity created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                entityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                entityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                entityId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEntityRequest"];
            };
        };
        responses: {
            /** @description Updated entity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listChildEntities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                entityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Child entities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createChildEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                entityId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntityRequest"];
            };
        };
        responses: {
            /** @description Child entity created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadEntityImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                entityId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    image: string;
                };
            };
        };
        responses: {
            /** @description Entity with updated image_url. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteEntityImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                entityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity with image_url cleared. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listRelationships: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of relationships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRelationshipRequest"];
            };
        };
        responses: {
            /** @description Relationship created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                relationshipId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationship deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getWikiGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full wiki graph. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiGraphResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listMagicRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of magic rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagicRuleResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createMagicRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMagicRuleRequest"];
            };
        };
        responses: {
            /** @description Magic rule created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagicRuleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteMagicRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Magic rule deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateMagicRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMagicRuleRequest"];
            };
        };
        responses: {
            /** @description Updated magic rule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagicRuleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTimelineEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTimelineEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTimelineEventRequest"];
            };
        };
        responses: {
            /** @description Timeline event created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteTimelineEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline event deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTimelineEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTimelineEventRequest"];
            };
        };
        responses: {
            /** @description Updated timeline event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAPIKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of key hints (no raw keys). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    upsertAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertAPIKeyRequest"];
            };
        };
        responses: {
            /** @description Stored key hint. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listNovelStructures: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All structure templates ordered by sort_order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovelStructureResponse"][];
                };
            };
        };
    };
    scoreStructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StructureScoreRequest"];
            };
        };
        responses: {
            /** @description Ranked structure recommendations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureScoreResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProjectStructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current structure selection (null fields when none selected). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStructureResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateProjectStructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectStructureRequest"];
            };
        };
        responses: {
            /** @description Updated structure selection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStructureResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    autolink: {
        parameters: {
            query: {
                text: string;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of entity matches with character offsets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutolinkMatch"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
