// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAct = `-- name: CreateAct :one
INSERT INTO acts (project_id, title, summary, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, title, summary, sort_order, created_at, updated_at
`

type CreateActParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Title     string    `json:"title"`
	Summary   string    `json:"summary"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) CreateAct(ctx context.Context, arg CreateActParams) (Act, error) {
	row := q.db.QueryRow(ctx, createAct,
		arg.ProjectID,
		arg.Title,
		arg.Summary,
		arg.SortOrder,
	)
	var i Act
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Summary,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAct = `-- name: DeleteAct :exec
DELETE FROM acts WHERE id = $1
`

func (q *Queries) DeleteAct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAct, id)
	return err
}

const getAct = `-- name: GetAct :one
SELECT id, project_id, title, summary, sort_order, created_at, updated_at
FROM acts
WHERE id = $1
`

func (q *Queries) GetAct(ctx context.Context, id uuid.UUID) (Act, error) {
	row := q.db.QueryRow(ctx, getAct, id)
	var i Act
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Summary,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActsByProject = `-- name: ListActsByProject :many
SELECT id, project_id, title, summary, sort_order, created_at, updated_at
FROM acts
WHERE project_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListActsByProject(ctx context.Context, projectID uuid.UUID) ([]Act, error) {
	rows, err := q.db.Query(ctx, listActsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Act{}
	for rows.Next() {
		var i Act
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Summary,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAct = `-- name: UpdateAct :one
UPDATE acts
SET title      = COALESCE($2, title),
    summary    = COALESCE($3, summary),
    sort_order = COALESCE($4, sort_order),
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, summary, sort_order, created_at, updated_at
`

type UpdateActParams struct {
	ID        uuid.UUID   `json:"id"`
	Title     pgtype.Text `json:"title"`
	Summary   pgtype.Text `json:"summary"`
	SortOrder pgtype.Int4 `json:"sort_order"`
}

func (q *Queries) UpdateAct(ctx context.Context, arg UpdateActParams) (Act, error) {
	row := q.db.QueryRow(ctx, updateAct,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.SortOrder,
	)
	var i Act
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Summary,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
