// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminGetStats = `-- name: AdminGetStats :one
SELECT
    (SELECT COUNT(*)::INT FROM users)                   AS total_users,
    (SELECT COUNT(*)::INT FROM projects)                AS total_projects,
    (SELECT COUNT(*)::INT FROM scenes)                  AS total_scenes,
    (SELECT COUNT(*)::INT FROM ai_usage)                AS total_ai_calls,
    COALESCE(SUM(au.prompt_tokens + au.completion_tokens), 0)::BIGINT AS total_tokens,
    COALESCE(SUM(au.cost_usd), 0)                       AS total_cost_usd
FROM ai_usage au
`

type AdminGetStatsRow struct {
	TotalUsers    int32       `json:"total_users"`
	TotalProjects int32       `json:"total_projects"`
	TotalScenes   int32       `json:"total_scenes"`
	TotalAiCalls  int32       `json:"total_ai_calls"`
	TotalTokens   int64       `json:"total_tokens"`
	TotalCostUsd  interface{} `json:"total_cost_usd"`
}

func (q *Queries) AdminGetStats(ctx context.Context) (AdminGetStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetStats)
	var i AdminGetStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.TotalProjects,
		&i.TotalScenes,
		&i.TotalAiCalls,
		&i.TotalTokens,
		&i.TotalCostUsd,
	)
	return i, err
}

const adminListAIUsage = `-- name: AdminListAIUsage :many
SELECT
    u.id          AS user_id,
    u.email,
    u.display_name,
    COUNT(*)::INT AS call_count,
    COALESCE(SUM(au.prompt_tokens + au.completion_tokens), 0)::BIGINT AS total_tokens,
    COALESCE(SUM(au.cost_usd), 0) AS total_cost_usd
FROM ai_usage au
JOIN users u ON u.id = au.user_id
WHERE au.created_at >= now() - INTERVAL '30 days'
GROUP BY u.id
ORDER BY total_tokens DESC
LIMIT 50
`

type AdminListAIUsageRow struct {
	UserID       uuid.UUID   `json:"user_id"`
	Email        string      `json:"email"`
	DisplayName  string      `json:"display_name"`
	CallCount    int32       `json:"call_count"`
	TotalTokens  int64       `json:"total_tokens"`
	TotalCostUsd interface{} `json:"total_cost_usd"`
}

// Per-user AI usage totals for the last 30 days, ordered by token spend.
func (q *Queries) AdminListAIUsage(ctx context.Context) ([]AdminListAIUsageRow, error) {
	rows, err := q.db.Query(ctx, adminListAIUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAIUsageRow{}
	for rows.Next() {
		var i AdminListAIUsageRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.CallCount,
			&i.TotalTokens,
			&i.TotalCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many

SELECT
    u.id,
    u.email,
    u.display_name,
    u.role,
    u.plan,
    u.created_at,
    COUNT(p.id)::INT AS project_count
FROM users u
LEFT JOIN projects p ON p.owner_id = u.id
GROUP BY u.id
ORDER BY u.created_at DESC
LIMIT  $1
OFFSET $2
`

type AdminListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type AdminListUsersRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	Role         UserRole           `json:"role"`
	Plan         string             `json:"plan"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProjectCount int32              `json:"project_count"`
}

// Admin queries — all behind RequireRole(RoleAdmin) in the handler.
// No per-user scoping: these span the full dataset.
// Paginated user list with per-user project count.
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.Plan,
			&i.CreatedAt,
			&i.ProjectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetUserPlan = `-- name: AdminSetUserPlan :exec
UPDATE users SET plan = $2, updated_at = now() WHERE id = $1
`

type AdminSetUserPlanParams struct {
	ID   uuid.UUID `json:"id"`
	Plan string    `json:"plan"`
}

func (q *Queries) AdminSetUserPlan(ctx context.Context, arg AdminSetUserPlanParams) error {
	_, err := q.db.Exec(ctx, adminSetUserPlan, arg.ID, arg.Plan)
	return err
}

const adminSetUserRole = `-- name: AdminSetUserRole :exec
UPDATE users SET role = $2, updated_at = now() WHERE id = $1
`

type AdminSetUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role UserRole  `json:"role"`
}

func (q *Queries) AdminSetUserRole(ctx context.Context, arg AdminSetUserRoleParams) error {
	_, err := q.db.Exec(ctx, adminSetUserRole, arg.ID, arg.Role)
	return err
}
