// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_context_pins.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createContextPin = `-- name: CreateContextPin :one
INSERT INTO ai_context_pins (project_id, user_id, pin_type, ref_id, include_mode)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, user_id, pin_type, ref_id)
DO UPDATE SET include_mode = EXCLUDED.include_mode
RETURNING id, project_id, user_id, pin_type, ref_id, include_mode, sort_order, created_at
`

type CreateContextPinParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	UserID      uuid.UUID `json:"user_id"`
	PinType     string    `json:"pin_type"`
	RefID       uuid.UUID `json:"ref_id"`
	IncludeMode string    `json:"include_mode"`
}

func (q *Queries) CreateContextPin(ctx context.Context, arg CreateContextPinParams) (AiContextPin, error) {
	row := q.db.QueryRow(ctx, createContextPin,
		arg.ProjectID,
		arg.UserID,
		arg.PinType,
		arg.RefID,
		arg.IncludeMode,
	)
	var i AiContextPin
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.PinType,
		&i.RefID,
		&i.IncludeMode,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContextPin = `-- name: DeleteContextPin :exec
DELETE FROM ai_context_pins
WHERE id = $1 AND project_id = $2 AND user_id = $3
`

type DeleteContextPinParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteContextPin(ctx context.Context, arg DeleteContextPinParams) error {
	_, err := q.db.Exec(ctx, deleteContextPin, arg.ID, arg.ProjectID, arg.UserID)
	return err
}

const listContextPins = `-- name: ListContextPins :many

SELECT id, project_id, user_id, pin_type, ref_id, include_mode, sort_order, created_at
FROM   ai_context_pins
WHERE  project_id = $1
  AND  user_id    = $2
ORDER  BY sort_order ASC, created_at ASC
`

type ListContextPinsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

// ========================
// AI Context Pins (C2)
// ========================
// Per-user, per-project pins that are injected into the AI context window on
// every call. Writers can pin wiki entities, chapters, or scenes to ensure
// Nexus always has a specific piece of information in scope.
func (q *Queries) ListContextPins(ctx context.Context, arg ListContextPinsParams) ([]AiContextPin, error) {
	rows, err := q.db.Query(ctx, listContextPins, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiContextPin{}
	for rows.Next() {
		var i AiContextPin
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.PinType,
			&i.RefID,
			&i.IncludeMode,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
