// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_usage.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectUsageSummary = `-- name: GetProjectUsageSummary :one
SELECT
    COALESCE(SUM(prompt_tokens + completion_tokens), 0)::bigint        AS total_tokens,
    COALESCE(SUM(cost_usd), 0)                                         AS total_cost_usd,
    COALESCE(SUM(CASE WHEN created_at >= date_trunc('month', now())
                      THEN prompt_tokens + completion_tokens END), 0)::bigint  AS monthly_tokens,
    COALESCE(SUM(CASE WHEN created_at >= date_trunc('month', now())
                      THEN cost_usd END), 0)                           AS monthly_cost_usd,
    COUNT(CASE WHEN created_at >= date_trunc('month', now()) THEN 1 END)::bigint AS calls_this_month
FROM ai_usage
WHERE project_id = $1
`

type GetProjectUsageSummaryRow struct {
	TotalTokens    int64       `json:"total_tokens"`
	TotalCostUsd   interface{} `json:"total_cost_usd"`
	MonthlyTokens  int64       `json:"monthly_tokens"`
	MonthlyCostUsd interface{} `json:"monthly_cost_usd"`
	CallsThisMonth int64       `json:"calls_this_month"`
}

func (q *Queries) GetProjectUsageSummary(ctx context.Context, projectID uuid.UUID) (GetProjectUsageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getProjectUsageSummary, projectID)
	var i GetProjectUsageSummaryRow
	err := row.Scan(
		&i.TotalTokens,
		&i.TotalCostUsd,
		&i.MonthlyTokens,
		&i.MonthlyCostUsd,
		&i.CallsThisMonth,
	)
	return i, err
}

const insertUsage = `-- name: InsertUsage :exec
INSERT INTO ai_usage (user_id, project_id, model, prompt_tokens, completion_tokens, cost_usd)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertUsageParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	ProjectID        uuid.UUID      `json:"project_id"`
	Model            string         `json:"model"`
	PromptTokens     int32          `json:"prompt_tokens"`
	CompletionTokens int32          `json:"completion_tokens"`
	CostUsd          pgtype.Numeric `json:"cost_usd"`
}

func (q *Queries) InsertUsage(ctx context.Context, arg InsertUsageParams) error {
	_, err := q.db.Exec(ctx, insertUsage,
		arg.UserID,
		arg.ProjectID,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostUsd,
	)
	return err
}
