// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annotations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnotation = `-- name: CreateAnnotation :one
INSERT INTO manuscript_annotations
    (project_id, scene_id, author_id, start_char, end_char, body, type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, scene_id, author_id, start_char, end_char, body, type, resolved, resolved_by, created_at
`

type CreateAnnotationParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	SceneID   uuid.UUID `json:"scene_id"`
	AuthorID  uuid.UUID `json:"author_id"`
	StartChar int32     `json:"start_char"`
	EndChar   int32     `json:"end_char"`
	Body      string    `json:"body"`
	Type      string    `json:"type"`
}

func (q *Queries) CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (ManuscriptAnnotation, error) {
	row := q.db.QueryRow(ctx, createAnnotation,
		arg.ProjectID,
		arg.SceneID,
		arg.AuthorID,
		arg.StartChar,
		arg.EndChar,
		arg.Body,
		arg.Type,
	)
	var i ManuscriptAnnotation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SceneID,
		&i.AuthorID,
		&i.StartChar,
		&i.EndChar,
		&i.Body,
		&i.Type,
		&i.Resolved,
		&i.ResolvedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnnotation = `-- name: DeleteAnnotation :exec
DELETE FROM manuscript_annotations
WHERE  id = $1 AND project_id = $2
`

type DeleteAnnotationParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteAnnotation(ctx context.Context, arg DeleteAnnotationParams) error {
	_, err := q.db.Exec(ctx, deleteAnnotation, arg.ID, arg.ProjectID)
	return err
}

const getAnnotation = `-- name: GetAnnotation :one
SELECT id, project_id, scene_id, author_id, start_char, end_char, body, type, resolved, resolved_by, created_at
FROM   manuscript_annotations
WHERE  id = $1 AND project_id = $2
`

type GetAnnotationParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetAnnotation(ctx context.Context, arg GetAnnotationParams) (ManuscriptAnnotation, error) {
	row := q.db.QueryRow(ctx, getAnnotation, arg.ID, arg.ProjectID)
	var i ManuscriptAnnotation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SceneID,
		&i.AuthorID,
		&i.StartChar,
		&i.EndChar,
		&i.Body,
		&i.Type,
		&i.Resolved,
		&i.ResolvedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAnnotationsByScene = `-- name: ListAnnotationsByScene :many

SELECT
    a.id, a.project_id, a.scene_id, a.author_id,
    u.display_name  AS author_name,
    a.start_char, a.end_char, a.body, a.type,
    a.resolved, a.resolved_by, a.created_at
FROM   manuscript_annotations a
JOIN   users u ON u.id = a.author_id
WHERE  a.scene_id = $1
ORDER  BY a.start_char ASC
`

type ListAnnotationsBySceneRow struct {
	ID         uuid.UUID          `json:"id"`
	ProjectID  uuid.UUID          `json:"project_id"`
	SceneID    uuid.UUID          `json:"scene_id"`
	AuthorID   uuid.UUID          `json:"author_id"`
	AuthorName string             `json:"author_name"`
	StartChar  int32              `json:"start_char"`
	EndChar    int32              `json:"end_char"`
	Body       string             `json:"body"`
	Type       string             `json:"type"`
	Resolved   bool               `json:"resolved"`
	ResolvedBy pgtype.UUID        `json:"resolved_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// ============================
// Manuscript Annotations (C3.4)
// ============================
// Per-scene inline notes, suggestions, and questions left by reviewers/editors.
// Resolved by the project owner only.
func (q *Queries) ListAnnotationsByScene(ctx context.Context, sceneID uuid.UUID) ([]ListAnnotationsBySceneRow, error) {
	rows, err := q.db.Query(ctx, listAnnotationsByScene, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnotationsBySceneRow{}
	for rows.Next() {
		var i ListAnnotationsBySceneRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SceneID,
			&i.AuthorID,
			&i.AuthorName,
			&i.StartChar,
			&i.EndChar,
			&i.Body,
			&i.Type,
			&i.Resolved,
			&i.ResolvedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAnnotation = `-- name: ResolveAnnotation :one
UPDATE manuscript_annotations
SET    resolved = true, resolved_by = $3
WHERE  id = $1 AND project_id = $2
RETURNING id, project_id, scene_id, author_id, start_char, end_char, body, type, resolved, resolved_by, created_at
`

type ResolveAnnotationParams struct {
	ID         uuid.UUID   `json:"id"`
	ProjectID  uuid.UUID   `json:"project_id"`
	ResolvedBy pgtype.UUID `json:"resolved_by"`
}

func (q *Queries) ResolveAnnotation(ctx context.Context, arg ResolveAnnotationParams) (ManuscriptAnnotation, error) {
	row := q.db.QueryRow(ctx, resolveAnnotation, arg.ID, arg.ProjectID, arg.ResolvedBy)
	var i ManuscriptAnnotation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SceneID,
		&i.AuthorID,
		&i.StartChar,
		&i.EndChar,
		&i.Body,
		&i.Type,
		&i.Resolved,
		&i.ResolvedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateAnnotationBody = `-- name: UpdateAnnotationBody :one
UPDATE manuscript_annotations
SET    body = $3
WHERE  id = $1 AND project_id = $2
RETURNING id, project_id, scene_id, author_id, start_char, end_char, body, type, resolved, resolved_by, created_at
`

type UpdateAnnotationBodyParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Body      string    `json:"body"`
}

func (q *Queries) UpdateAnnotationBody(ctx context.Context, arg UpdateAnnotationBodyParams) (ManuscriptAnnotation, error) {
	row := q.db.QueryRow(ctx, updateAnnotationBody, arg.ID, arg.ProjectID, arg.Body)
	var i ManuscriptAnnotation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SceneID,
		&i.AuthorID,
		&i.StartChar,
		&i.EndChar,
		&i.Body,
		&i.Type,
		&i.Resolved,
		&i.ResolvedBy,
		&i.CreatedAt,
	)
	return i, err
}
