// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM user_api_keys
WHERE user_id = $1 AND provider = $2
`

type DeleteAPIKeyParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.UserID, arg.Provider)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, user_id, provider, encrypted_key, key_hint, created_at, updated_at, force_non_streaming
FROM user_api_keys
WHERE user_id = $1 AND provider = $2
`

type GetAPIKeyParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (UserApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.UserID, arg.Provider)
	var i UserApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.EncryptedKey,
		&i.KeyHint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForceNonStreaming,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, user_id, provider, encrypted_key, key_hint, created_at, updated_at, force_non_streaming
FROM user_api_keys
WHERE user_id = $1
ORDER BY provider ASC
`

func (q *Queries) ListAPIKeys(ctx context.Context, userID uuid.UUID) ([]UserApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserApiKey{}
	for rows.Next() {
		var i UserApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.EncryptedKey,
			&i.KeyHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ForceNonStreaming,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAPIKey = `-- name: UpsertAPIKey :one
INSERT INTO user_api_keys (user_id, provider, encrypted_key, key_hint)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, provider) DO UPDATE
    SET encrypted_key = EXCLUDED.encrypted_key,
        key_hint      = EXCLUDED.key_hint,
        updated_at    = now()
RETURNING id, user_id, provider, encrypted_key, key_hint, created_at, updated_at, force_non_streaming
`

type UpsertAPIKeyParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Provider     string    `json:"provider"`
	EncryptedKey []byte    `json:"encrypted_key"`
	KeyHint      string    `json:"key_hint"`
}

func (q *Queries) UpsertAPIKey(ctx context.Context, arg UpsertAPIKeyParams) (UserApiKey, error) {
	row := q.db.QueryRow(ctx, upsertAPIKey,
		arg.UserID,
		arg.Provider,
		arg.EncryptedKey,
		arg.KeyHint,
	)
	var i UserApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.EncryptedKey,
		&i.KeyHint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ForceNonStreaming,
	)
	return i, err
}
