// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chapters.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChapter = `-- name: CreateChapter :one
INSERT INTO chapters (project_id, title, summary, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, title, summary, sort_order, created_at, updated_at
`

type CreateChapterParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Title     string    `json:"title"`
	Summary   string    `json:"summary"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, createChapter,
		arg.ProjectID,
		arg.Title,
		arg.Summary,
		arg.SortOrder,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Summary,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChapter = `-- name: DeleteChapter :exec
DELETE FROM chapters WHERE id = $1
`

func (q *Queries) DeleteChapter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChapter, id)
	return err
}

const getChapter = `-- name: GetChapter :one
SELECT id, project_id, title, summary, sort_order, created_at, updated_at
FROM chapters
WHERE id = $1
`

func (q *Queries) GetChapter(ctx context.Context, id uuid.UUID) (Chapter, error) {
	row := q.db.QueryRow(ctx, getChapter, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Summary,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChaptersByProject = `-- name: ListChaptersByProject :many
SELECT id, project_id, title, summary, sort_order, created_at, updated_at
FROM chapters
WHERE project_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListChaptersByProject(ctx context.Context, projectID uuid.UUID) ([]Chapter, error) {
	rows, err := q.db.Query(ctx, listChaptersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Summary,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChapter = `-- name: UpdateChapter :one
UPDATE chapters
SET title = COALESCE($2, title),
    summary = COALESCE($3, summary),
    sort_order = COALESCE($4, sort_order),
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, summary, sort_order, created_at, updated_at
`

type UpdateChapterParams struct {
	ID        uuid.UUID   `json:"id"`
	Title     pgtype.Text `json:"title"`
	Summary   pgtype.Text `json:"summary"`
	SortOrder pgtype.Int4 `json:"sort_order"`
}

func (q *Queries) UpdateChapter(ctx context.Context, arg UpdateChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, updateChapter,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.SortOrder,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Summary,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
