// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chapter_summaries.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteChapterSummariesByBranch = `-- name: DeleteChapterSummariesByBranch :exec
DELETE FROM chapter_summaries
WHERE branch_name = $1
  AND chapter_id IN (
      SELECT c.id FROM chapters c WHERE c.project_id = $2
  )
`

type DeleteChapterSummariesByBranchParams struct {
	BranchName string    `json:"branch_name"`
	ProjectID  uuid.UUID `json:"project_id"`
}

// Called by Canonize to remove the merged branch's summary rows.
func (q *Queries) DeleteChapterSummariesByBranch(ctx context.Context, arg DeleteChapterSummariesByBranchParams) error {
	_, err := q.db.Exec(ctx, deleteChapterSummariesByBranch, arg.BranchName, arg.ProjectID)
	return err
}

const deleteProjectActiveBranchByBranch = `-- name: DeleteProjectActiveBranchByBranch :exec
DELETE FROM project_active_branch
WHERE project_id = $1 AND branch_name = $2
`

type DeleteProjectActiveBranchByBranchParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	BranchName string    `json:"branch_name"`
}

// Called by Canonize to clear all user pointers to the merged branch.
func (q *Queries) DeleteProjectActiveBranchByBranch(ctx context.Context, arg DeleteProjectActiveBranchByBranchParams) error {
	_, err := q.db.Exec(ctx, deleteProjectActiveBranchByBranch, arg.ProjectID, arg.BranchName)
	return err
}

const getChapterSummary = `-- name: GetChapterSummary :one
SELECT chapter_id, branch_name, ai_summary, stale, updated_at
FROM chapter_summaries
WHERE chapter_id = $1 AND branch_name = $2
`

type GetChapterSummaryParams struct {
	ChapterID  uuid.UUID `json:"chapter_id"`
	BranchName string    `json:"branch_name"`
}

func (q *Queries) GetChapterSummary(ctx context.Context, arg GetChapterSummaryParams) (ChapterSummary, error) {
	row := q.db.QueryRow(ctx, getChapterSummary, arg.ChapterID, arg.BranchName)
	var i ChapterSummary
	err := row.Scan(
		&i.ChapterID,
		&i.BranchName,
		&i.AiSummary,
		&i.Stale,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectActiveBranch = `-- name: GetProjectActiveBranch :one
SELECT branch_name
FROM project_active_branch
WHERE project_id = $1 AND user_id = $2
`

type GetProjectActiveBranchParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectActiveBranch(ctx context.Context, arg GetProjectActiveBranchParams) (string, error) {
	row := q.db.QueryRow(ctx, getProjectActiveBranch, arg.ProjectID, arg.UserID)
	var branch_name string
	err := row.Scan(&branch_name)
	return branch_name, err
}

const listChapterSummariesByProject = `-- name: ListChapterSummariesByProject :many
SELECT cs.chapter_id,
       cs.branch_name,
       cs.ai_summary,
       cs.stale,
       cs.updated_at,
       c.title      AS chapter_title,
       c.sort_order AS chapter_sort_order
FROM chapter_summaries cs
JOIN chapters c ON c.id = cs.chapter_id
WHERE c.project_id  = $1
  AND cs.branch_name = $2
ORDER BY c.sort_order ASC
`

type ListChapterSummariesByProjectParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	BranchName string    `json:"branch_name"`
}

type ListChapterSummariesByProjectRow struct {
	ChapterID        uuid.UUID          `json:"chapter_id"`
	BranchName       string             `json:"branch_name"`
	AiSummary        string             `json:"ai_summary"`
	Stale            bool               `json:"stale"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ChapterTitle     string             `json:"chapter_title"`
	ChapterSortOrder int32              `json:"chapter_sort_order"`
}

// Returns all summary rows for chapters belonging to a project, ordered by
// chapter sort_order. Used by BuildContext to assemble the AI context window.
func (q *Queries) ListChapterSummariesByProject(ctx context.Context, arg ListChapterSummariesByProjectParams) ([]ListChapterSummariesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listChapterSummariesByProject, arg.ProjectID, arg.BranchName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChapterSummariesByProjectRow{}
	for rows.Next() {
		var i ListChapterSummariesByProjectRow
		if err := rows.Scan(
			&i.ChapterID,
			&i.BranchName,
			&i.AiSummary,
			&i.Stale,
			&i.UpdatedAt,
			&i.ChapterTitle,
			&i.ChapterSortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChapterSummaryStale = `-- name: MarkChapterSummaryStale :exec
INSERT INTO chapter_summaries (chapter_id, branch_name, stale, updated_at)
VALUES ($1, $2, TRUE, NOW())
ON CONFLICT (chapter_id, branch_name)
DO UPDATE SET stale      = TRUE,
              updated_at = NOW()
`

type MarkChapterSummaryStaleParams struct {
	ChapterID  uuid.UUID `json:"chapter_id"`
	BranchName string    `json:"branch_name"`
}

func (q *Queries) MarkChapterSummaryStale(ctx context.Context, arg MarkChapterSummaryStaleParams) error {
	_, err := q.db.Exec(ctx, markChapterSummaryStale, arg.ChapterID, arg.BranchName)
	return err
}

const upsertChapterSummary = `-- name: UpsertChapterSummary :exec
INSERT INTO chapter_summaries (chapter_id, branch_name, ai_summary, stale, updated_at)
VALUES ($1, $2, $3, FALSE, NOW())
ON CONFLICT (chapter_id, branch_name)
DO UPDATE SET ai_summary = EXCLUDED.ai_summary,
              stale      = FALSE,
              updated_at = NOW()
`

type UpsertChapterSummaryParams struct {
	ChapterID  uuid.UUID `json:"chapter_id"`
	BranchName string    `json:"branch_name"`
	AiSummary  string    `json:"ai_summary"`
}

func (q *Queries) UpsertChapterSummary(ctx context.Context, arg UpsertChapterSummaryParams) error {
	_, err := q.db.Exec(ctx, upsertChapterSummary, arg.ChapterID, arg.BranchName, arg.AiSummary)
	return err
}

const upsertProjectActiveBranch = `-- name: UpsertProjectActiveBranch :exec
INSERT INTO project_active_branch (project_id, user_id, branch_name, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (project_id, user_id)
DO UPDATE SET branch_name = EXCLUDED.branch_name,
              updated_at  = NOW()
`

type UpsertProjectActiveBranchParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	UserID     uuid.UUID `json:"user_id"`
	BranchName string    `json:"branch_name"`
}

func (q *Queries) UpsertProjectActiveBranch(ctx context.Context, arg UpsertProjectActiveBranchParams) error {
	_, err := q.db.Exec(ctx, upsertProjectActiveBranch, arg.ProjectID, arg.UserID, arg.BranchName)
	return err
}
