// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collaboration.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :exec
UPDATE project_invites SET accepted_at = now() WHERE token = $1
`

func (q *Queries) AcceptInvite(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, acceptInvite, token)
	return err
}

const createCollaborator = `-- name: CreateCollaborator :one
INSERT INTO project_collaborators (project_id, user_id, role, branch_name, clone_path, invited_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING project_id, user_id, joined_at, role, branch_name, clone_path, invited_by
`

type CreateCollaboratorParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	UserID     uuid.UUID   `json:"user_id"`
	Role       string      `json:"role"`
	BranchName string      `json:"branch_name"`
	ClonePath  string      `json:"clone_path"`
	InvitedBy  pgtype.UUID `json:"invited_by"`
}

func (q *Queries) CreateCollaborator(ctx context.Context, arg CreateCollaboratorParams) (ProjectCollaborator, error) {
	row := q.db.QueryRow(ctx, createCollaborator,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.BranchName,
		arg.ClonePath,
		arg.InvitedBy,
	)
	var i ProjectCollaborator
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.JoinedAt,
		&i.Role,
		&i.BranchName,
		&i.ClonePath,
		&i.InvitedBy,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO project_invites (project_id, invited_by, email, role, token, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, invited_by, email, role, token, accepted_at, expires_at, created_at
`

type CreateInviteParams struct {
	ProjectID uuid.UUID          `json:"project_id"`
	InvitedBy uuid.UUID          `json:"invited_by"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (ProjectInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ProjectID,
		arg.InvitedBy,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.ExpiresAt,
	)
	var i ProjectInvite
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM project_invites WHERE id = $1 AND project_id = $2
`

type DeleteInviteParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) error {
	_, err := q.db.Exec(ctx, deleteInvite, arg.ID, arg.ProjectID)
	return err
}

const getCollaborator = `-- name: GetCollaborator :one
SELECT project_id, user_id, joined_at, role, branch_name, clone_path, invited_by FROM project_collaborators WHERE project_id = $1 AND user_id = $2
`

type GetCollaboratorParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCollaborator(ctx context.Context, arg GetCollaboratorParams) (ProjectCollaborator, error) {
	row := q.db.QueryRow(ctx, getCollaborator, arg.ProjectID, arg.UserID)
	var i ProjectCollaborator
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.JoinedAt,
		&i.Role,
		&i.BranchName,
		&i.ClonePath,
		&i.InvitedBy,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, project_id, invited_by, email, role, token, accepted_at, expires_at, created_at FROM project_invites WHERE token = $1
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (ProjectInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i ProjectInvite
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const isCollaborator = `-- name: IsCollaborator :one
SELECT EXISTS (
  SELECT 1 FROM project_collaborators WHERE project_id = $1 AND user_id = $2
) AS exists
`

type IsCollaboratorParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) IsCollaborator(ctx context.Context, arg IsCollaboratorParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCollaborator, arg.ProjectID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCollaborators = `-- name: ListCollaborators :many
SELECT project_id, user_id, joined_at, role, branch_name, clone_path, invited_by FROM project_collaborators WHERE project_id = $1 ORDER BY joined_at
`

func (q *Queries) ListCollaborators(ctx context.Context, projectID uuid.UUID) ([]ProjectCollaborator, error) {
	rows, err := q.db.Query(ctx, listCollaborators, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectCollaborator{}
	for rows.Next() {
		var i ProjectCollaborator
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.JoinedAt,
			&i.Role,
			&i.BranchName,
			&i.ClonePath,
			&i.InvitedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvites = `-- name: ListPendingInvites :many
SELECT id, project_id, invited_by, email, role, token, accepted_at, expires_at, created_at FROM project_invites
WHERE project_id = $1
  AND accepted_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvites(ctx context.Context, projectID uuid.UUID) ([]ProjectInvite, error) {
	rows, err := q.db.Query(ctx, listPendingInvites, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectInvite{}
	for rows.Next() {
		var i ProjectInvite
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.InvitedBy,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.AcceptedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollaborator = `-- name: RemoveCollaborator :exec
DELETE FROM project_collaborators WHERE project_id = $1 AND user_id = $2
`

type RemoveCollaboratorParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveCollaborator(ctx context.Context, arg RemoveCollaboratorParams) error {
	_, err := q.db.Exec(ctx, removeCollaborator, arg.ProjectID, arg.UserID)
	return err
}
