// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export_jobs.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getExportJob = `-- name: GetExportJob :one
SELECT id, project_id, user_id, format, status, minio_key, error_msg, expires_at, created_at, updated_at
FROM export_jobs
WHERE id = $1
`

func (q *Queries) GetExportJob(ctx context.Context, id uuid.UUID) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJob, id)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Format,
		&i.Status,
		&i.MinioKey,
		&i.ErrorMsg,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertExportJob = `-- name: InsertExportJob :one
INSERT INTO export_jobs (project_id, user_id, format)
VALUES ($1, $2, $3)
RETURNING id, project_id, user_id, format, status, minio_key, error_msg, expires_at, created_at, updated_at
`

type InsertExportJobParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Format    string    `json:"format"`
}

func (q *Queries) InsertExportJob(ctx context.Context, arg InsertExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, insertExportJob, arg.ProjectID, arg.UserID, arg.Format)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Format,
		&i.Status,
		&i.MinioKey,
		&i.ErrorMsg,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExportJobsByProject = `-- name: ListExportJobsByProject :many
SELECT id, project_id, user_id, format, status, minio_key, error_msg, expires_at, created_at, updated_at
FROM export_jobs
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) ListExportJobsByProject(ctx context.Context, projectID uuid.UUID) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listExportJobsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportJob{}
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Format,
			&i.Status,
			&i.MinioKey,
			&i.ErrorMsg,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExportJobDone = `-- name: UpdateExportJobDone :exec
UPDATE export_jobs
SET status     = 'done',
    minio_key  = $2,
    expires_at = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateExportJobDoneParams struct {
	ID        uuid.UUID          `json:"id"`
	MinioKey  pgtype.Text        `json:"minio_key"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateExportJobDone(ctx context.Context, arg UpdateExportJobDoneParams) error {
	_, err := q.db.Exec(ctx, updateExportJobDone, arg.ID, arg.MinioKey, arg.ExpiresAt)
	return err
}

const updateExportJobFailed = `-- name: UpdateExportJobFailed :exec
UPDATE export_jobs
SET status    = 'failed',
    error_msg = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateExportJobFailedParams struct {
	ID       uuid.UUID   `json:"id"`
	ErrorMsg pgtype.Text `json:"error_msg"`
}

func (q *Queries) UpdateExportJobFailed(ctx context.Context, arg UpdateExportJobFailedParams) error {
	_, err := q.db.Exec(ctx, updateExportJobFailed, arg.ID, arg.ErrorMsg)
	return err
}

const updateExportJobProcessing = `-- name: UpdateExportJobProcessing :exec
UPDATE export_jobs
SET status     = 'processing',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateExportJobProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateExportJobProcessing, id)
	return err
}
