// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guide_steps.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const completeGuideStep = `-- name: CompleteGuideStep :one
UPDATE guide_steps
SET completed_at = NOW(),
    data         = $3,
    updated_at   = NOW()
WHERE project_id = $1
  AND step_key   = $2
RETURNING project_id, step_key, data, completed_at, created_at, updated_at
`

type CompleteGuideStepParams struct {
	ProjectID uuid.UUID       `json:"project_id"`
	StepKey   string          `json:"step_key"`
	Data      json.RawMessage `json:"data"`
}

func (q *Queries) CompleteGuideStep(ctx context.Context, arg CompleteGuideStepParams) (GuideStep, error) {
	row := q.db.QueryRow(ctx, completeGuideStep, arg.ProjectID, arg.StepKey, arg.Data)
	var i GuideStep
	err := row.Scan(
		&i.ProjectID,
		&i.StepKey,
		&i.Data,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuideStep = `-- name: GetGuideStep :one
SELECT project_id, step_key, data, completed_at, created_at, updated_at
FROM guide_steps
WHERE project_id = $1
  AND step_key   = $2
`

type GetGuideStepParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	StepKey   string    `json:"step_key"`
}

func (q *Queries) GetGuideStep(ctx context.Context, arg GetGuideStepParams) (GuideStep, error) {
	row := q.db.QueryRow(ctx, getGuideStep, arg.ProjectID, arg.StepKey)
	var i GuideStep
	err := row.Scan(
		&i.ProjectID,
		&i.StepKey,
		&i.Data,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuideSteps = `-- name: ListGuideSteps :many
SELECT project_id, step_key, data, completed_at, created_at, updated_at
FROM guide_steps
WHERE project_id = $1
ORDER BY CASE step_key
    WHEN 'premise'     THEN 1
    WHEN 'characters'  THEN 2
    WHEN 'world'       THEN 3
    WHEN 'outline'     THEN 4
    WHEN 'first_scene' THEN 5
    ELSE 99
END
`

func (q *Queries) ListGuideSteps(ctx context.Context, projectID uuid.UUID) ([]GuideStep, error) {
	rows, err := q.db.Query(ctx, listGuideSteps, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuideStep{}
	for rows.Next() {
		var i GuideStep
		if err := rows.Scan(
			&i.ProjectID,
			&i.StepKey,
			&i.Data,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGuideStep = `-- name: UpsertGuideStep :one
INSERT INTO guide_steps (project_id, step_key, data, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (project_id, step_key) DO UPDATE
    SET data       = EXCLUDED.data,
        updated_at = NOW()
RETURNING project_id, step_key, data, completed_at, created_at, updated_at
`

type UpsertGuideStepParams struct {
	ProjectID uuid.UUID       `json:"project_id"`
	StepKey   string          `json:"step_key"`
	Data      json.RawMessage `json:"data"`
}

func (q *Queries) UpsertGuideStep(ctx context.Context, arg UpsertGuideStepParams) (GuideStep, error) {
	row := q.db.QueryRow(ctx, upsertGuideStep, arg.ProjectID, arg.StepKey, arg.Data)
	var i GuideStep
	err := row.Scan(
		&i.ProjectID,
		&i.StepKey,
		&i.Data,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
