// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merge_requests.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMergeRequest = `-- name: CreateMergeRequest :one
INSERT INTO merge_requests (project_id, from_branch, to_branch, title, description, requested_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, from_branch, to_branch, title, description, requested_by, status, reviewer_note, created_at, resolved_at
`

type CreateMergeRequestParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	FromBranch  string    `json:"from_branch"`
	ToBranch    string    `json:"to_branch"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	RequestedBy uuid.UUID `json:"requested_by"`
}

func (q *Queries) CreateMergeRequest(ctx context.Context, arg CreateMergeRequestParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, createMergeRequest,
		arg.ProjectID,
		arg.FromBranch,
		arg.ToBranch,
		arg.Title,
		arg.Description,
		arg.RequestedBy,
	)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromBranch,
		&i.ToBranch,
		&i.Title,
		&i.Description,
		&i.RequestedBy,
		&i.Status,
		&i.ReviewerNote,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getMergeRequest = `-- name: GetMergeRequest :one
SELECT mr.id, mr.project_id, mr.from_branch, mr.to_branch, mr.title, mr.description,
       mr.requested_by, u.display_name AS requester_name,
       mr.status, mr.reviewer_note, mr.created_at, mr.resolved_at
FROM merge_requests mr
JOIN users u ON u.id = mr.requested_by
WHERE mr.id = $1
`

type GetMergeRequestRow struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	FromBranch    string             `json:"from_branch"`
	ToBranch      string             `json:"to_branch"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	RequesterName string             `json:"requester_name"`
	Status        string             `json:"status"`
	ReviewerNote  string             `json:"reviewer_note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) GetMergeRequest(ctx context.Context, id uuid.UUID) (GetMergeRequestRow, error) {
	row := q.db.QueryRow(ctx, getMergeRequest, id)
	var i GetMergeRequestRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromBranch,
		&i.ToBranch,
		&i.Title,
		&i.Description,
		&i.RequestedBy,
		&i.RequesterName,
		&i.Status,
		&i.ReviewerNote,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getOpenMRByBranch = `-- name: GetOpenMRByBranch :one
SELECT id FROM merge_requests
WHERE project_id = $1 AND from_branch = $2 AND status = 'open'
LIMIT 1
`

type GetOpenMRByBranchParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	FromBranch string    `json:"from_branch"`
}

func (q *Queries) GetOpenMRByBranch(ctx context.Context, arg GetOpenMRByBranchParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOpenMRByBranch, arg.ProjectID, arg.FromBranch)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listMergeRequests = `-- name: ListMergeRequests :many
SELECT mr.id, mr.project_id, mr.from_branch, mr.to_branch, mr.title, mr.description,
       mr.requested_by, u.display_name AS requester_name,
       mr.status, mr.reviewer_note, mr.created_at, mr.resolved_at
FROM merge_requests mr
JOIN users u ON u.id = mr.requested_by
WHERE mr.project_id = $1
ORDER BY mr.created_at DESC
`

type ListMergeRequestsRow struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	FromBranch    string             `json:"from_branch"`
	ToBranch      string             `json:"to_branch"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	RequesterName string             `json:"requester_name"`
	Status        string             `json:"status"`
	ReviewerNote  string             `json:"reviewer_note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) ListMergeRequests(ctx context.Context, projectID uuid.UUID) ([]ListMergeRequestsRow, error) {
	rows, err := q.db.Query(ctx, listMergeRequests, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMergeRequestsRow{}
	for rows.Next() {
		var i ListMergeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromBranch,
			&i.ToBranch,
			&i.Title,
			&i.Description,
			&i.RequestedBy,
			&i.RequesterName,
			&i.Status,
			&i.ReviewerNote,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMergeRequestStatus = `-- name: UpdateMergeRequestStatus :one
UPDATE merge_requests
SET status = $2, reviewer_note = $3, resolved_at = CASE WHEN $2 != 'open' THEN now() ELSE NULL END
WHERE id = $1
RETURNING id, project_id, from_branch, to_branch, title, description, requested_by, status, reviewer_note, created_at, resolved_at
`

type UpdateMergeRequestStatusParams struct {
	ID           uuid.UUID `json:"id"`
	Status       string    `json:"status"`
	ReviewerNote string    `json:"reviewer_note"`
}

func (q *Queries) UpdateMergeRequestStatus(ctx context.Context, arg UpdateMergeRequestStatusParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, updateMergeRequestStatus, arg.ID, arg.Status, arg.ReviewerNote)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromBranch,
		&i.ToBranch,
		&i.Title,
		&i.Description,
		&i.RequestedBy,
		&i.Status,
		&i.ReviewerNote,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
