// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleViewer UserRole = "viewer"
	UserRoleAuthor UserRole = "author"
	UserRoleAdmin  UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Act struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Title     string             `json:"title"`
	Summary   string             `json:"summary"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Chapter struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Title     string             `json:"title"`
	Summary   string             `json:"summary"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ActID     uuid.UUID          `json:"act_id"`
}

type Fork struct {
	ID              uuid.UUID          `json:"id"`
	SourceProjectID uuid.UUID          `json:"source_project_id"`
	ForkedProjectID uuid.UUID          `json:"forked_project_id"`
	BranchName      string             `json:"branch_name"`
	SourceCommitSha string             `json:"source_commit_sha"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          uuid.UUID          `json:"id"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Genres      []string           `json:"genres"`
	GitRepoPath string             `json:"git_repo_path"`
	Archived    bool               `json:"archived"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectCollaborator struct {
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      UserRole           `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Scene struct {
	ID           uuid.UUID          `json:"id"`
	ChapterID    uuid.UUID          `json:"chapter_id"`
	Title        string             `json:"title"`
	Content      string             `json:"content"`
	Pov          string             `json:"pov"`
	Tense        string             `json:"tense"`
	Tags         []string           `json:"tags"`
	Summary      string             `json:"summary"`
	SummaryStale bool               `json:"summary_stale"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	WordCount    int32              `json:"word_count"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserApiKey struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Provider     string             `json:"provider"`
	EncryptedKey []byte             `json:"encrypted_key"`
	KeyHint      string             `json:"key_hint"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WikiEntity struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	ParentEntityID pgtype.UUID        `json:"parent_entity_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Summary        string             `json:"summary"`
	Attributes     json.RawMessage    `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WikiMagicRule struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WikiRelationship struct {
	ID           uuid.UUID          `json:"id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	FromEntityID uuid.UUID          `json:"from_entity_id"`
	ToEntityID   uuid.UUID          `json:"to_entity_id"`
	Type         string             `json:"type"`
	Description  string             `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type WikiTimelineEvent struct {
	ID                uuid.UUID          `json:"id"`
	ProjectID         uuid.UUID          `json:"project_id"`
	EntityID          pgtype.UUID        `json:"entity_id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	Era               string             `json:"era"`
	Year              pgtype.Int4        `json:"year"`
	Month             pgtype.Int4        `json:"month"`
	Day               pgtype.Int4        `json:"day"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AnchorEventID     pgtype.UUID        `json:"anchor_event_id"`
	AnchorOffsetYear  pgtype.Int4        `json:"anchor_offset_year"`
	AnchorOffsetMonth pgtype.Int4        `json:"anchor_offset_month"`
	AnchorOffsetDay   pgtype.Int4        `json:"anchor_offset_day"`
}
