// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, project_id, type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, project_id, type, payload, read_at, created_at
`

type CreateNotificationParams struct {
	UserID    uuid.UUID       `json:"user_id"`
	ProjectID pgtype.UUID     `json:"project_id"`
	Type      string          `json:"type"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.ProjectID,
		arg.Type,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Type,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, project_id, type, payload, read_at, created_at
FROM notifications
WHERE user_id = $1
  AND (read_at IS NULL OR created_at > now() - INTERVAL '30 days')
ORDER BY
  (read_at IS NULL) DESC,
  created_at DESC
LIMIT 50
`

// Returns all unread notifications + the last 20 read ones, newest first.
func (q *Queries) ListNotifications(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Type,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = now()
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = now()
WHERE id = $1
  AND user_id = $2
  AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const unreadCount = `-- name: UnreadCount :one
SELECT COUNT(*)::int AS count
FROM notifications
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) UnreadCount(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, unreadCount, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}
