// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: novel_structures.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNovelStructure = `-- name: GetNovelStructure :one
SELECT id, name, description, phases, strengths, risks, sort_order
FROM novel_structures
WHERE id = $1
`

func (q *Queries) GetNovelStructure(ctx context.Context, id uuid.UUID) (NovelStructure, error) {
	row := q.db.QueryRow(ctx, getNovelStructure, id)
	var i NovelStructure
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Phases,
		&i.Strengths,
		&i.Risks,
		&i.SortOrder,
	)
	return i, err
}

const getProjectStructure = `-- name: GetProjectStructure :one
SELECT
    p.structure_id,
    ns.name        AS structure_name,
    ns.phases      AS phases,
    p.structure_custom
FROM projects p
LEFT JOIN novel_structures ns ON ns.id = p.structure_id
WHERE p.id = $1
`

type GetProjectStructureRow struct {
	StructureID     pgtype.UUID `json:"structure_id"`
	StructureName   pgtype.Text `json:"structure_name"`
	Phases          []byte      `json:"phases"`
	StructureCustom []byte      `json:"structure_custom"`
}

func (q *Queries) GetProjectStructure(ctx context.Context, id uuid.UUID) (GetProjectStructureRow, error) {
	row := q.db.QueryRow(ctx, getProjectStructure, id)
	var i GetProjectStructureRow
	err := row.Scan(
		&i.StructureID,
		&i.StructureName,
		&i.Phases,
		&i.StructureCustom,
	)
	return i, err
}

const listNovelStructures = `-- name: ListNovelStructures :many
SELECT id, name, description, phases, strengths, risks, sort_order
FROM novel_structures
ORDER BY sort_order
`

func (q *Queries) ListNovelStructures(ctx context.Context) ([]NovelStructure, error) {
	rows, err := q.db.Query(ctx, listNovelStructures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NovelStructure{}
	for rows.Next() {
		var i NovelStructure
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Phases,
			&i.Strengths,
			&i.Risks,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectStructure = `-- name: UpdateProjectStructure :one
UPDATE projects
SET structure_id     = $2,
    structure_custom = $3,
    updated_at       = now()
WHERE id = $1
RETURNING structure_id, structure_custom
`

type UpdateProjectStructureParams struct {
	ID              uuid.UUID   `json:"id"`
	StructureID     pgtype.UUID `json:"structure_id"`
	StructureCustom []byte      `json:"structure_custom"`
}

type UpdateProjectStructureRow struct {
	StructureID     pgtype.UUID `json:"structure_id"`
	StructureCustom []byte      `json:"structure_custom"`
}

func (q *Queries) UpdateProjectStructure(ctx context.Context, arg UpdateProjectStructureParams) (UpdateProjectStructureRow, error) {
	row := q.db.QueryRow(ctx, updateProjectStructure, arg.ID, arg.StructureID, arg.StructureCustom)
	var i UpdateProjectStructureRow
	err := row.Scan(&i.StructureID, &i.StructureCustom)
	return i, err
}
