// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProject = `-- name: ArchiveProject :exec
UPDATE projects SET archived = true, updated_at = now() WHERE id = $1
`

func (q *Queries) ArchiveProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveProject, id)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (owner_id, title, description, genres, git_repo_path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, title, description, genres, git_repo_path, archived, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Genres      []string  `json:"genres"`
	GitRepoPath string    `json:"git_repo_path"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Genres,
		arg.GitRepoPath,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Genres,
		&i.GitRepoPath,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, owner_id, title, description, genres, git_repo_path, archived, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Genres,
		&i.GitRepoPath,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT id, owner_id, title, description, genres, git_repo_path, archived, created_at, updated_at
FROM projects
WHERE owner_id = $1 AND archived = false
ORDER BY updated_at DESC
`

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Genres,
			&i.GitRepoPath,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    updated_at = now()
WHERE id = $1
RETURNING id, owner_id, title, description, genres, git_repo_path, archived, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Title, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Genres,
		&i.GitRepoPath,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
