// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProject = `-- name: ArchiveProject :exec
UPDATE projects SET archived = true, updated_at = now() WHERE id = $1
`

func (q *Queries) ArchiveProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveProject, id)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (owner_id, title, description, genres, git_repo_path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, title, description, genres, git_repo_path, archived, created_at, updated_at, structure_id, structure_custom, ai_instructions
`

type CreateProjectParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Genres      []string  `json:"genres"`
	GitRepoPath string    `json:"git_repo_path"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Genres,
		arg.GitRepoPath,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Genres,
		&i.GitRepoPath,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StructureID,
		&i.StructureCustom,
		&i.AiInstructions,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getAIInstructions = `-- name: GetAIInstructions :one
SELECT ai_instructions FROM projects WHERE id = $1
`

func (q *Queries) GetAIInstructions(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAIInstructions, id)
	var ai_instructions string
	err := row.Scan(&ai_instructions)
	return ai_instructions, err
}

const getProject = `-- name: GetProject :one
SELECT id, owner_id, title, description, genres, git_repo_path, archived, created_at, updated_at, structure_id, structure_custom, ai_instructions
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Genres,
		&i.GitRepoPath,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StructureID,
		&i.StructureCustom,
		&i.AiInstructions,
	)
	return i, err
}

const getProjectStats = `-- name: GetProjectStats :one
SELECT
    COUNT(DISTINCT s.id)::INT         AS scene_count,
    COUNT(DISTINCT c.id)::INT         AS chapter_count,
    COALESCE(SUM(s.word_count), 0)::INT AS total_word_count,
    GREATEST(
        p.updated_at,
        MAX(c.updated_at),
        MAX(s.updated_at)
    )                                  AS last_updated_at
FROM projects p
LEFT JOIN acts a    ON a.project_id = p.id
LEFT JOIN chapters c ON c.act_id   = a.id
LEFT JOIN scenes s   ON s.chapter_id = c.id
WHERE p.id = $1
GROUP BY p.id, p.updated_at
`

type GetProjectStatsRow struct {
	SceneCount     int32       `json:"scene_count"`
	ChapterCount   int32       `json:"chapter_count"`
	TotalWordCount int32       `json:"total_word_count"`
	LastUpdatedAt  interface{} `json:"last_updated_at"`
}

func (q *Queries) GetProjectStats(ctx context.Context, id uuid.UUID) (GetProjectStatsRow, error) {
	row := q.db.QueryRow(ctx, getProjectStats, id)
	var i GetProjectStatsRow
	err := row.Scan(
		&i.SceneCount,
		&i.ChapterCount,
		&i.TotalWordCount,
		&i.LastUpdatedAt,
	)
	return i, err
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT id, owner_id, title, description, genres, git_repo_path, archived, created_at, updated_at, structure_id, structure_custom, ai_instructions
FROM projects
WHERE owner_id = $1 AND archived = false
ORDER BY updated_at DESC
`

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Genres,
			&i.GitRepoPath,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StructureID,
			&i.StructureCustom,
			&i.AiInstructions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT DISTINCT p.id, p.owner_id, p.title, p.description, p.genres, p.git_repo_path,
       p.archived, p.created_at, p.updated_at, p.structure_id, p.structure_custom, p.ai_instructions
FROM projects p
LEFT JOIN project_collaborators pc ON pc.project_id = p.id AND pc.user_id = $1
WHERE p.archived = false
  AND (p.owner_id = $1 OR pc.user_id IS NOT NULL)
ORDER BY p.updated_at DESC
`

func (q *Queries) ListProjectsForUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Genres,
			&i.GitRepoPath,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StructureID,
			&i.StructureCustom,
			&i.AiInstructions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIInstructions = `-- name: UpdateAIInstructions :exec
UPDATE projects SET ai_instructions = $2, updated_at = now() WHERE id = $1
`

type UpdateAIInstructionsParams struct {
	ID             uuid.UUID `json:"id"`
	AiInstructions string    `json:"ai_instructions"`
}

func (q *Queries) UpdateAIInstructions(ctx context.Context, arg UpdateAIInstructionsParams) error {
	_, err := q.db.Exec(ctx, updateAIInstructions, arg.ID, arg.AiInstructions)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    updated_at = now()
WHERE id = $1
RETURNING id, owner_id, title, description, genres, git_repo_path, archived, created_at, updated_at, structure_id, structure_custom, ai_instructions
`

type UpdateProjectParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Title, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Genres,
		&i.GitRepoPath,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StructureID,
		&i.StructureCustom,
		&i.AiInstructions,
	)
	return i, err
}
