// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectPrompt = `-- name: CreateProjectPrompt :one
INSERT INTO project_prompts (project_id, name, category, content, system_content, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, category, content, system_content, sort_order, created_at, updated_at
`

type CreateProjectPromptParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	Name          string    `json:"name"`
	Category      string    `json:"category"`
	Content       string    `json:"content"`
	SystemContent string    `json:"system_content"`
	SortOrder     int32     `json:"sort_order"`
}

func (q *Queries) CreateProjectPrompt(ctx context.Context, arg CreateProjectPromptParams) (ProjectPrompt, error) {
	row := q.db.QueryRow(ctx, createProjectPrompt,
		arg.ProjectID,
		arg.Name,
		arg.Category,
		arg.Content,
		arg.SystemContent,
		arg.SortOrder,
	)
	var i ProjectPrompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Content,
		&i.SystemContent,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectPrompt = `-- name: DeleteProjectPrompt :exec
DELETE FROM project_prompts
WHERE id = $1
`

func (q *Queries) DeleteProjectPrompt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectPrompt, id)
	return err
}

const getProjectPrompt = `-- name: GetProjectPrompt :one
SELECT id, project_id, name, category, content, system_content, sort_order, created_at, updated_at
FROM project_prompts
WHERE id = $1
`

func (q *Queries) GetProjectPrompt(ctx context.Context, id uuid.UUID) (ProjectPrompt, error) {
	row := q.db.QueryRow(ctx, getProjectPrompt, id)
	var i ProjectPrompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Content,
		&i.SystemContent,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectPrompts = `-- name: ListProjectPrompts :many
SELECT id, project_id, name, category, content, system_content, sort_order, created_at, updated_at
FROM project_prompts
WHERE project_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListProjectPrompts(ctx context.Context, projectID uuid.UUID) ([]ProjectPrompt, error) {
	rows, err := q.db.Query(ctx, listProjectPrompts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectPrompt{}
	for rows.Next() {
		var i ProjectPrompt
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Category,
			&i.Content,
			&i.SystemContent,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectPrompt = `-- name: UpdateProjectPrompt :one
UPDATE project_prompts
SET name           = COALESCE($2, name),
    category       = COALESCE($3, category),
    content        = COALESCE($4, content),
    system_content = COALESCE($5, system_content),
    sort_order     = COALESCE($6, sort_order),
    updated_at     = now()
WHERE id = $1
RETURNING id, project_id, name, category, content, system_content, sort_order, created_at, updated_at
`

type UpdateProjectPromptParams struct {
	ID            uuid.UUID   `json:"id"`
	Name          pgtype.Text `json:"name"`
	Category      pgtype.Text `json:"category"`
	Content       pgtype.Text `json:"content"`
	SystemContent pgtype.Text `json:"system_content"`
	SortOrder     pgtype.Int4 `json:"sort_order"`
}

func (q *Queries) UpdateProjectPrompt(ctx context.Context, arg UpdateProjectPromptParams) (ProjectPrompt, error) {
	row := q.db.QueryRow(ctx, updateProjectPrompt,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Content,
		arg.SystemContent,
		arg.SortOrder,
	)
	var i ProjectPrompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Content,
		&i.SystemContent,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
