// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: research_notes.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createResearchNote = `-- name: CreateResearchNote :one
INSERT INTO research_notes (project_id, user_id, title, body, source_url, tags)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, user_id, title, body, source_url, tags, created_at, updated_at
`

type CreateResearchNoteParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	SourceUrl string    `json:"source_url"`
	Tags      []string  `json:"tags"`
}

type CreateResearchNoteRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	SourceUrl string             `json:"source_url"`
	Tags      []string           `json:"tags"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateResearchNote(ctx context.Context, arg CreateResearchNoteParams) (CreateResearchNoteRow, error) {
	row := q.db.QueryRow(ctx, createResearchNote,
		arg.ProjectID,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.SourceUrl,
		arg.Tags,
	)
	var i CreateResearchNoteRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.SourceUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResearchNote = `-- name: DeleteResearchNote :exec
DELETE FROM research_notes
WHERE  id         = $1
  AND  project_id = $2
`

type DeleteResearchNoteParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteResearchNote(ctx context.Context, arg DeleteResearchNoteParams) error {
	_, err := q.db.Exec(ctx, deleteResearchNote, arg.ID, arg.ProjectID)
	return err
}

const getResearchNote = `-- name: GetResearchNote :one
SELECT id, project_id, user_id, title, body, source_url, tags, created_at, updated_at
FROM   research_notes
WHERE  id         = $1
  AND  project_id = $2
`

type GetResearchNoteParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type GetResearchNoteRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	SourceUrl string             `json:"source_url"`
	Tags      []string           `json:"tags"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Project-scoped fetch; used by CRUD handlers.
func (q *Queries) GetResearchNote(ctx context.Context, arg GetResearchNoteParams) (GetResearchNoteRow, error) {
	row := q.db.QueryRow(ctx, getResearchNote, arg.ID, arg.ProjectID)
	var i GetResearchNoteRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.SourceUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResearchNoteByID = `-- name: GetResearchNoteByID :one
SELECT id, project_id, user_id, title, body, source_url, tags, created_at, updated_at
FROM   research_notes
WHERE  id = $1
`

type GetResearchNoteByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	SourceUrl string             `json:"source_url"`
	Tags      []string           `json:"tags"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// ID-only fetch; used by the AI context builder (no project_id needed — UUIDs are unguessable).
func (q *Queries) GetResearchNoteByID(ctx context.Context, id uuid.UUID) (GetResearchNoteByIDRow, error) {
	row := q.db.QueryRow(ctx, getResearchNoteByID, id)
	var i GetResearchNoteByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.SourceUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResearchNotes = `-- name: ListResearchNotes :many

SELECT id, project_id, user_id, title, body, source_url, tags, created_at, updated_at
FROM   research_notes
WHERE  project_id = $1
ORDER  BY updated_at DESC
`

type ListResearchNotesRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	SourceUrl string             `json:"source_url"`
	Tags      []string           `json:"tags"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// ============================
// Research Notes (C2)
// ============================
// Per-project scratchpad entries for web quotes, worldbuilding facts,
// craft references, etc.  Notes are project-wide (not per-user) so all
// collaborators on a project share the same pool.
func (q *Queries) ListResearchNotes(ctx context.Context, projectID uuid.UUID) ([]ListResearchNotesRow, error) {
	rows, err := q.db.Query(ctx, listResearchNotes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResearchNotesRow{}
	for rows.Next() {
		var i ListResearchNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.SourceUrl,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResearchNote = `-- name: UpdateResearchNote :one
UPDATE research_notes
SET title      = $3,
    body       = $4,
    source_url = $5,
    tags       = $6,
    updated_at = NOW()
WHERE  id         = $1
  AND  project_id = $2
RETURNING id, project_id, user_id, title, body, source_url, tags, created_at, updated_at
`

type UpdateResearchNoteParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	SourceUrl string    `json:"source_url"`
	Tags      []string  `json:"tags"`
}

type UpdateResearchNoteRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	SourceUrl string             `json:"source_url"`
	Tags      []string           `json:"tags"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateResearchNote(ctx context.Context, arg UpdateResearchNoteParams) (UpdateResearchNoteRow, error) {
	row := q.db.QueryRow(ctx, updateResearchNote,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Body,
		arg.SourceUrl,
		arg.Tags,
	)
	var i UpdateResearchNoteRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.SourceUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
