// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scenes.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScene = `-- name: CreateScene :one
INSERT INTO scenes (chapter_id, title, pov, tense, tags, summary, sort_order, word_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, chapter_id, title, pov, tense, tags, summary, summary_stale, sort_order, created_at, updated_at, word_count
`

type CreateSceneParams struct {
	ChapterID uuid.UUID `json:"chapter_id"`
	Title     string    `json:"title"`
	Pov       string    `json:"pov"`
	Tense     string    `json:"tense"`
	Tags      []string  `json:"tags"`
	Summary   string    `json:"summary"`
	SortOrder int32     `json:"sort_order"`
	WordCount int32     `json:"word_count"`
}

func (q *Queries) CreateScene(ctx context.Context, arg CreateSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, createScene,
		arg.ChapterID,
		arg.Title,
		arg.Pov,
		arg.Tense,
		arg.Tags,
		arg.Summary,
		arg.SortOrder,
		arg.WordCount,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Title,
		&i.Pov,
		&i.Tense,
		&i.Tags,
		&i.Summary,
		&i.SummaryStale,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WordCount,
	)
	return i, err
}

const deleteScene = `-- name: DeleteScene :exec
DELETE FROM scenes WHERE id = $1
`

func (q *Queries) DeleteScene(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScene, id)
	return err
}

const getScene = `-- name: GetScene :one
SELECT id, chapter_id, title, pov, tense, tags, summary, summary_stale, sort_order, created_at, updated_at, word_count
FROM scenes
WHERE id = $1
`

func (q *Queries) GetScene(ctx context.Context, id uuid.UUID) (Scene, error) {
	row := q.db.QueryRow(ctx, getScene, id)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Title,
		&i.Pov,
		&i.Tense,
		&i.Tags,
		&i.Summary,
		&i.SummaryStale,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WordCount,
	)
	return i, err
}

const listScenesByChapter = `-- name: ListScenesByChapter :many
SELECT id, chapter_id, title, pov, tense, tags, summary, summary_stale, sort_order, created_at, updated_at, word_count
FROM scenes
WHERE chapter_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListScenesByChapter(ctx context.Context, chapterID uuid.UUID) ([]Scene, error) {
	rows, err := q.db.Query(ctx, listScenesByChapter, chapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scene{}
	for rows.Next() {
		var i Scene
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.Title,
			&i.Pov,
			&i.Tense,
			&i.Tags,
			&i.Summary,
			&i.SummaryStale,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WordCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScene = `-- name: UpdateScene :one
UPDATE scenes
SET title = COALESCE($2, title),
    pov = COALESCE($3, pov),
    tense = COALESCE($4, tense),
    tags = COALESCE($5, tags),
    summary = COALESCE($6, summary),
    summary_stale = COALESCE($7, summary_stale),
    sort_order = COALESCE($8, sort_order),
    word_count = COALESCE($9, word_count),
    updated_at = now()
WHERE id = $1
RETURNING id, chapter_id, title, pov, tense, tags, summary, summary_stale, sort_order, created_at, updated_at, word_count
`

type UpdateSceneParams struct {
	ID           uuid.UUID   `json:"id"`
	Title        pgtype.Text `json:"title"`
	Pov          pgtype.Text `json:"pov"`
	Tense        pgtype.Text `json:"tense"`
	Tags         []string    `json:"tags"`
	Summary      pgtype.Text `json:"summary"`
	SummaryStale pgtype.Bool `json:"summary_stale"`
	SortOrder    pgtype.Int4 `json:"sort_order"`
	WordCount    pgtype.Int4 `json:"word_count"`
}

func (q *Queries) UpdateScene(ctx context.Context, arg UpdateSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, updateScene,
		arg.ID,
		arg.Title,
		arg.Pov,
		arg.Tense,
		arg.Tags,
		arg.Summary,
		arg.SummaryStale,
		arg.SortOrder,
		arg.WordCount,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Title,
		&i.Pov,
		&i.Tense,
		&i.Tags,
		&i.Summary,
		&i.SummaryStale,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WordCount,
	)
	return i, err
}
