// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: threads.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenThreadsByChapter = `-- name: CountOpenThreadsByChapter :many
SELECT s.chapter_id, COUNT(*)::int AS open_thread_count
FROM story_threads st
JOIN scenes s ON s.id = st.opened_at_scene_id
WHERE st.project_id = $1
  AND st.closed_at_scene_id IS NULL
GROUP BY s.chapter_id
`

type CountOpenThreadsByChapterRow struct {
	ChapterID       uuid.UUID `json:"chapter_id"`
	OpenThreadCount int32     `json:"open_thread_count"`
}

// Returns, for each chapter in the project, how many open (unresolved) threads
// were opened within a scene belonging to that chapter.
func (q *Queries) CountOpenThreadsByChapter(ctx context.Context, projectID uuid.UUID) ([]CountOpenThreadsByChapterRow, error) {
	rows, err := q.db.Query(ctx, countOpenThreadsByChapter, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOpenThreadsByChapterRow{}
	for rows.Next() {
		var i CountOpenThreadsByChapterRow
		if err := rows.Scan(&i.ChapterID, &i.OpenThreadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createThread = `-- name: CreateThread :one
INSERT INTO story_threads (project_id, title, type, notes, opened_at_scene_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, title, type, notes, opened_at_scene_id, closed_at_scene_id, created_at, updated_at
`

type CreateThreadParams struct {
	ProjectID       uuid.UUID   `json:"project_id"`
	Title           string      `json:"title"`
	Type            string      `json:"type"`
	Notes           string      `json:"notes"`
	OpenedAtSceneID pgtype.UUID `json:"opened_at_scene_id"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (StoryThread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.ProjectID,
		arg.Title,
		arg.Type,
		arg.Notes,
		arg.OpenedAtSceneID,
	)
	var i StoryThread
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.Notes,
		&i.OpenedAtSceneID,
		&i.ClosedAtSceneID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :exec
DELETE FROM story_threads WHERE id = $1
`

func (q *Queries) DeleteThread(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteThread, id)
	return err
}

const getThread = `-- name: GetThread :one
SELECT id, project_id, title, type, notes, opened_at_scene_id, closed_at_scene_id, created_at, updated_at FROM story_threads WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id uuid.UUID) (StoryThread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i StoryThread
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.Notes,
		&i.OpenedAtSceneID,
		&i.ClosedAtSceneID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenThreadsByProject = `-- name: ListOpenThreadsByProject :many
SELECT st.id, st.project_id, st.title, st.type, st.notes,
       st.opened_at_scene_id, st.closed_at_scene_id, st.created_at, st.updated_at,
       COALESCE(c.title, '') AS chapter_title
FROM story_threads st
LEFT JOIN scenes s  ON s.id  = st.opened_at_scene_id
LEFT JOIN chapters c ON c.id = s.chapter_id
WHERE st.project_id = $1
  AND st.closed_at_scene_id IS NULL
ORDER BY st.created_at DESC
LIMIT 10
`

type ListOpenThreadsByProjectRow struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	Title           string             `json:"title"`
	Type            string             `json:"type"`
	Notes           string             `json:"notes"`
	OpenedAtSceneID pgtype.UUID        `json:"opened_at_scene_id"`
	ClosedAtSceneID pgtype.UUID        `json:"closed_at_scene_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ChapterTitle    string             `json:"chapter_title"`
}

// Returns open (unresolved) story threads for a project with their opening chapter title,
// ordered most-recently-opened first, capped at 10 for context injection.
func (q *Queries) ListOpenThreadsByProject(ctx context.Context, projectID uuid.UUID) ([]ListOpenThreadsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listOpenThreadsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenThreadsByProjectRow{}
	for rows.Next() {
		var i ListOpenThreadsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.Notes,
			&i.OpenedAtSceneID,
			&i.ClosedAtSceneID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChapterTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsByProject = `-- name: ListThreadsByProject :many
SELECT id, project_id, title, type, notes, opened_at_scene_id, closed_at_scene_id, created_at, updated_at FROM story_threads
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListThreadsByProject(ctx context.Context, projectID uuid.UUID) ([]StoryThread, error) {
	rows, err := q.db.Query(ctx, listThreadsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoryThread{}
	for rows.Next() {
		var i StoryThread
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.Notes,
			&i.OpenedAtSceneID,
			&i.ClosedAtSceneID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThread = `-- name: UpdateThread :one
UPDATE story_threads
SET title               = COALESCE($2, title),
    type                = COALESCE($3, type),
    notes               = COALESCE($4, notes),
    opened_at_scene_id  = COALESCE($5, opened_at_scene_id),
    closed_at_scene_id  = $6,
    updated_at          = NOW()
WHERE id = $1
RETURNING id, project_id, title, type, notes, opened_at_scene_id, closed_at_scene_id, created_at, updated_at
`

type UpdateThreadParams struct {
	ID              uuid.UUID   `json:"id"`
	Title           pgtype.Text `json:"title"`
	Type            pgtype.Text `json:"type"`
	Notes           pgtype.Text `json:"notes"`
	OpenedAtSceneID pgtype.UUID `json:"opened_at_scene_id"`
	ClosedAtSceneID pgtype.UUID `json:"closed_at_scene_id"`
}

func (q *Queries) UpdateThread(ctx context.Context, arg UpdateThreadParams) (StoryThread, error) {
	row := q.db.QueryRow(ctx, updateThread,
		arg.ID,
		arg.Title,
		arg.Type,
		arg.Notes,
		arg.OpenedAtSceneID,
		arg.ClosedAtSceneID,
	)
	var i StoryThread
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.Notes,
		&i.OpenedAtSceneID,
		&i.ClosedAtSceneID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
