// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: threads.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createThread = `-- name: CreateThread :one
INSERT INTO story_threads (project_id, title, type, notes, opened_at_scene_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, title, type, notes, opened_at_scene_id, closed_at_scene_id, created_at, updated_at
`

type CreateThreadParams struct {
	ProjectID       uuid.UUID   `json:"project_id"`
	Title           string      `json:"title"`
	Type            string      `json:"type"`
	Notes           string      `json:"notes"`
	OpenedAtSceneID pgtype.UUID `json:"opened_at_scene_id"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (StoryThread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.ProjectID,
		arg.Title,
		arg.Type,
		arg.Notes,
		arg.OpenedAtSceneID,
	)
	var i StoryThread
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.Notes,
		&i.OpenedAtSceneID,
		&i.ClosedAtSceneID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :exec
DELETE FROM story_threads WHERE id = $1
`

func (q *Queries) DeleteThread(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteThread, id)
	return err
}

const getThread = `-- name: GetThread :one
SELECT id, project_id, title, type, notes, opened_at_scene_id, closed_at_scene_id, created_at, updated_at FROM story_threads WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id uuid.UUID) (StoryThread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i StoryThread
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.Notes,
		&i.OpenedAtSceneID,
		&i.ClosedAtSceneID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listThreadsByProject = `-- name: ListThreadsByProject :many
SELECT id, project_id, title, type, notes, opened_at_scene_id, closed_at_scene_id, created_at, updated_at FROM story_threads
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListThreadsByProject(ctx context.Context, projectID uuid.UUID) ([]StoryThread, error) {
	rows, err := q.db.Query(ctx, listThreadsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoryThread{}
	for rows.Next() {
		var i StoryThread
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.Notes,
			&i.OpenedAtSceneID,
			&i.ClosedAtSceneID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThread = `-- name: UpdateThread :one
UPDATE story_threads
SET title               = COALESCE($2, title),
    type                = COALESCE($3, type),
    notes               = COALESCE($4, notes),
    opened_at_scene_id  = COALESCE($5, opened_at_scene_id),
    closed_at_scene_id  = $6,
    updated_at          = NOW()
WHERE id = $1
RETURNING id, project_id, title, type, notes, opened_at_scene_id, closed_at_scene_id, created_at, updated_at
`

type UpdateThreadParams struct {
	ID              uuid.UUID   `json:"id"`
	Title           pgtype.Text `json:"title"`
	Type            pgtype.Text `json:"type"`
	Notes           pgtype.Text `json:"notes"`
	OpenedAtSceneID pgtype.UUID `json:"opened_at_scene_id"`
	ClosedAtSceneID pgtype.UUID `json:"closed_at_scene_id"`
}

func (q *Queries) UpdateThread(ctx context.Context, arg UpdateThreadParams) (StoryThread, error) {
	row := q.db.QueryRow(ctx, updateThread,
		arg.ID,
		arg.Title,
		arg.Type,
		arg.Notes,
		arg.OpenedAtSceneID,
		arg.ClosedAtSceneID,
	)
	var i StoryThread
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.Notes,
		&i.OpenedAtSceneID,
		&i.ClosedAtSceneID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
