// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, display_name, role, plan, created_at, updated_at
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	DisplayName  string   `json:"display_name"`
	PasswordHash string   `json:"password_hash"`
	Role         UserRole `json:"role"`
}

type CreateUserRow struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Role        UserRole           `json:"role"`
	Plan        string             `json:"plan"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, password_hash, role, plan, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	Plan         string             `json:"plan"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, password_hash, role, plan, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	Plan         string             `json:"plan"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectGitPaths = `-- name: ListProjectGitPaths :many
SELECT git_repo_path FROM projects WHERE owner_id = $1 AND git_repo_path != ''
`

func (q *Queries) ListProjectGitPaths(ctx context.Context, ownerID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listProjectGitPaths, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var git_repo_path string
		if err := rows.Scan(&git_repo_path); err != nil {
			return nil, err
		}
		items = append(items, git_repo_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCollaboratorClonePaths = `-- name: ListUserCollaboratorClonePaths :many
SELECT clone_path
FROM project_collaborators
WHERE user_id = $1
  AND clone_path IS NOT NULL
  AND clone_path != ''
`

func (q *Queries) ListUserCollaboratorClonePaths(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserCollaboratorClonePaths, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var clone_path string
		if err := rows.Scan(&clone_path); err != nil {
			return nil, err
		}
		items = append(items, clone_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserExportMinioKeys = `-- name: ListUserExportMinioKeys :many
SELECT minio_key
FROM export_jobs
WHERE user_id = $1
  AND minio_key IS NOT NULL
  AND minio_key != ''
`

func (q *Queries) ListUserExportMinioKeys(ctx context.Context, userID uuid.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listUserExportMinioKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var minio_key pgtype.Text
		if err := rows.Scan(&minio_key); err != nil {
			return nil, err
		}
		items = append(items, minio_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWikiImageKeys = `-- name: ListUserWikiImageKeys :many
SELECT we.image_key
FROM wiki_entities we
JOIN projects p ON p.id = we.project_id
WHERE p.owner_id = $1
  AND we.image_key IS NOT NULL
  AND we.image_key != ''
`

func (q *Queries) ListUserWikiImageKeys(ctx context.Context, ownerID uuid.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listUserWikiImageKeys, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var image_key pgtype.Text
		if err := rows.Scan(&image_key); err != nil {
			return nil, err
		}
		items = append(items, image_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = COALESCE($2, display_name),
    email = COALESCE($3, email),
    updated_at = now()
WHERE id = $1
RETURNING id, email, display_name, role, plan, created_at, updated_at
`

type UpdateUserParams struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	Email       pgtype.Text `json:"email"`
}

type UpdateUserRow struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Role        UserRole           `json:"role"`
	Plan        string             `json:"plan"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName, arg.Email)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
