// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waitlist.sql

package sqlcgen

import (
	"context"
)

const createWaitlistSignup = `-- name: CreateWaitlistSignup :one

INSERT INTO waitlist_signups (email, what_they_write)
VALUES ($1, $2)
ON CONFLICT (email) DO UPDATE
    SET what_they_write = EXCLUDED.what_they_write
RETURNING id, email, what_they_write, created_at
`

type CreateWaitlistSignupParams struct {
	Email         string `json:"email"`
	WhatTheyWrite string `json:"what_they_write"`
}

// ============================
// Waitlist Signups (alpha pre-launch)
// ============================
// Upsert by email so duplicate submissions are idempotent.
func (q *Queries) CreateWaitlistSignup(ctx context.Context, arg CreateWaitlistSignupParams) (WaitlistSignup, error) {
	row := q.db.QueryRow(ctx, createWaitlistSignup, arg.Email, arg.WhatTheyWrite)
	var i WaitlistSignup
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.WhatTheyWrite,
		&i.CreatedAt,
	)
	return i, err
}

const listWaitlistSignups = `-- name: ListWaitlistSignups :many
SELECT id, email, what_they_write, created_at
FROM   waitlist_signups
ORDER  BY created_at DESC
`

func (q *Queries) ListWaitlistSignups(ctx context.Context) ([]WaitlistSignup, error) {
	rows, err := q.db.Query(ctx, listWaitlistSignups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaitlistSignup{}
	for rows.Next() {
		var i WaitlistSignup
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.WhatTheyWrite,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
