// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wiki.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearEntityImage = `-- name: ClearEntityImage :one
UPDATE wiki_entities
SET image_key  = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, parent_entity_id, type, name, summary, attributes, created_at, updated_at, image_key
`

type ClearEntityImageRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	ParentEntityID pgtype.UUID        `json:"parent_entity_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Summary        string             `json:"summary"`
	Attributes     json.RawMessage    `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImageKey       pgtype.Text        `json:"image_key"`
}

func (q *Queries) ClearEntityImage(ctx context.Context, id uuid.UUID) (ClearEntityImageRow, error) {
	row := q.db.QueryRow(ctx, clearEntityImage, id)
	var i ClearEntityImageRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentEntityID,
		&i.Type,
		&i.Name,
		&i.Summary,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageKey,
	)
	return i, err
}

const countUnsuppressedMentionsByEntity = `-- name: CountUnsuppressedMentionsByEntity :one
SELECT COUNT(*)::INT AS mention_count
FROM scene_entity_mentions
WHERE entity_id = $1 AND suppressed = FALSE
`

func (q *Queries) CountUnsuppressedMentionsByEntity(ctx context.Context, entityID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnsuppressedMentionsByEntity, entityID)
	var mention_count int32
	err := row.Scan(&mention_count)
	return mention_count, err
}

const createEntity = `-- name: CreateEntity :one


INSERT INTO wiki_entities (project_id, parent_entity_id, type, name, summary, attributes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, parent_entity_id, type, name, summary, attributes, created_at, updated_at, image_key
`

type CreateEntityParams struct {
	ProjectID      uuid.UUID       `json:"project_id"`
	ParentEntityID pgtype.UUID     `json:"parent_entity_id"`
	Type           string          `json:"type"`
	Name           string          `json:"name"`
	Summary        string          `json:"summary"`
	Attributes     json.RawMessage `json:"attributes"`
}

type CreateEntityRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	ParentEntityID pgtype.UUID        `json:"parent_entity_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Summary        string             `json:"summary"`
	Attributes     json.RawMessage    `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImageKey       pgtype.Text        `json:"image_key"`
}

// ========================
// Entities
// ========================
// entityColumns: wiki_entities queries list columns explicitly rather than
// using * — the embedding/embedding_updated_at columns (migration 037) are
// NULL until the background reembed worker runs, and pgvector-go's
// Vector.Scan doesn't handle a SQL NULL src, so SELECT */RETURNING * break
// entity reads/writes for any entity without a computed embedding yet.
// Same convention already used in chapter_summaries.sql/research_notes.sql.
func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (CreateEntityRow, error) {
	row := q.db.QueryRow(ctx, createEntity,
		arg.ProjectID,
		arg.ParentEntityID,
		arg.Type,
		arg.Name,
		arg.Summary,
		arg.Attributes,
	)
	var i CreateEntityRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentEntityID,
		&i.Type,
		&i.Name,
		&i.Summary,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageKey,
	)
	return i, err
}

const createMagicRule = `-- name: CreateMagicRule :one

INSERT INTO wiki_magic_rules (project_id, name, description, attributes)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, description, created_at, updated_at, attributes
`

type CreateMagicRuleParams struct {
	ProjectID   uuid.UUID       `json:"project_id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Attributes  json.RawMessage `json:"attributes"`
}

// ========================
// Magic Rules
// ========================
func (q *Queries) CreateMagicRule(ctx context.Context, arg CreateMagicRuleParams) (WikiMagicRule, error) {
	row := q.db.QueryRow(ctx, createMagicRule,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Attributes,
	)
	var i WikiMagicRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attributes,
	)
	return i, err
}

const createRelationship = `-- name: CreateRelationship :one

INSERT INTO wiki_relationships (project_id, from_entity_id, to_entity_id, type, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, from_entity_id, to_entity_id, type, description, created_at
`

type CreateRelationshipParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	FromEntityID uuid.UUID `json:"from_entity_id"`
	ToEntityID   uuid.UUID `json:"to_entity_id"`
	Type         string    `json:"type"`
	Description  string    `json:"description"`
}

// ========================
// Relationships
// ========================
func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (WikiRelationship, error) {
	row := q.db.QueryRow(ctx, createRelationship,
		arg.ProjectID,
		arg.FromEntityID,
		arg.ToEntityID,
		arg.Type,
		arg.Description,
	)
	var i WikiRelationship
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromEntityID,
		&i.ToEntityID,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createTimelineEvent = `-- name: CreateTimelineEvent :one

INSERT INTO wiki_timeline_events (
    project_id, entity_id, name, description, era,
    year, month, day,
    anchor_event_id, anchor_offset_year, anchor_offset_month, anchor_offset_day
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, project_id, entity_id, name, description, era, year, month, day, created_at, updated_at, anchor_event_id, anchor_offset_year, anchor_offset_month, anchor_offset_day
`

type CreateTimelineEventParams struct {
	ProjectID         uuid.UUID   `json:"project_id"`
	EntityID          pgtype.UUID `json:"entity_id"`
	Name              string      `json:"name"`
	Description       string      `json:"description"`
	Era               string      `json:"era"`
	Year              pgtype.Int4 `json:"year"`
	Month             pgtype.Int4 `json:"month"`
	Day               pgtype.Int4 `json:"day"`
	AnchorEventID     pgtype.UUID `json:"anchor_event_id"`
	AnchorOffsetYear  pgtype.Int4 `json:"anchor_offset_year"`
	AnchorOffsetMonth pgtype.Int4 `json:"anchor_offset_month"`
	AnchorOffsetDay   pgtype.Int4 `json:"anchor_offset_day"`
}

// ========================
// Timeline Events
// ========================
func (q *Queries) CreateTimelineEvent(ctx context.Context, arg CreateTimelineEventParams) (WikiTimelineEvent, error) {
	row := q.db.QueryRow(ctx, createTimelineEvent,
		arg.ProjectID,
		arg.EntityID,
		arg.Name,
		arg.Description,
		arg.Era,
		arg.Year,
		arg.Month,
		arg.Day,
		arg.AnchorEventID,
		arg.AnchorOffsetYear,
		arg.AnchorOffsetMonth,
		arg.AnchorOffsetDay,
	)
	var i WikiTimelineEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityID,
		&i.Name,
		&i.Description,
		&i.Era,
		&i.Year,
		&i.Month,
		&i.Day,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnchorEventID,
		&i.AnchorOffsetYear,
		&i.AnchorOffsetMonth,
		&i.AnchorOffsetDay,
	)
	return i, err
}

const deleteEntity = `-- name: DeleteEntity :exec
DELETE FROM wiki_entities WHERE id = $1
`

func (q *Queries) DeleteEntity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntity, id)
	return err
}

const deleteMagicRule = `-- name: DeleteMagicRule :exec
DELETE FROM wiki_magic_rules WHERE id = $1
`

func (q *Queries) DeleteMagicRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMagicRule, id)
	return err
}

const deleteRelationship = `-- name: DeleteRelationship :exec
DELETE FROM wiki_relationships WHERE id = $1
`

func (q *Queries) DeleteRelationship(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelationship, id)
	return err
}

const deleteSceneEntityMentions = `-- name: DeleteSceneEntityMentions :exec

DELETE FROM scene_entity_mentions
WHERE scene_id = $1 AND branch_name = $2
`

type DeleteSceneEntityMentionsParams struct {
	SceneID    uuid.UUID `json:"scene_id"`
	BranchName string    `json:"branch_name"`
}

// ========================
// Scene entity mentions
// ========================
func (q *Queries) DeleteSceneEntityMentions(ctx context.Context, arg DeleteSceneEntityMentionsParams) error {
	_, err := q.db.Exec(ctx, deleteSceneEntityMentions, arg.SceneID, arg.BranchName)
	return err
}

const deleteTimelineEvent = `-- name: DeleteTimelineEvent :exec
DELETE FROM wiki_timeline_events WHERE id = $1
`

func (q *Queries) DeleteTimelineEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimelineEvent, id)
	return err
}

const getEntitiesByNames = `-- name: GetEntitiesByNames :many
SELECT id, project_id, parent_entity_id, type, name, summary, attributes, created_at, updated_at, image_key
FROM wiki_entities
WHERE project_id = $1
  AND LOWER(name) = ANY($2::text[])
ORDER BY name ASC
`

type GetEntitiesByNamesParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Names     []string  `json:"names"`
}

type GetEntitiesByNamesRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	ParentEntityID pgtype.UUID        `json:"parent_entity_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Summary        string             `json:"summary"`
	Attributes     json.RawMessage    `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImageKey       pgtype.Text        `json:"image_key"`
}

func (q *Queries) GetEntitiesByNames(ctx context.Context, arg GetEntitiesByNamesParams) ([]GetEntitiesByNamesRow, error) {
	rows, err := q.db.Query(ctx, getEntitiesByNames, arg.ProjectID, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntitiesByNamesRow{}
	for rows.Next() {
		var i GetEntitiesByNamesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentEntityID,
			&i.Type,
			&i.Name,
			&i.Summary,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntity = `-- name: GetEntity :one
SELECT id, project_id, parent_entity_id, type, name, summary, attributes, created_at, updated_at, image_key
FROM wiki_entities WHERE id = $1
`

type GetEntityRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	ParentEntityID pgtype.UUID        `json:"parent_entity_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Summary        string             `json:"summary"`
	Attributes     json.RawMessage    `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImageKey       pgtype.Text        `json:"image_key"`
}

func (q *Queries) GetEntity(ctx context.Context, id uuid.UUID) (GetEntityRow, error) {
	row := q.db.QueryRow(ctx, getEntity, id)
	var i GetEntityRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentEntityID,
		&i.Type,
		&i.Name,
		&i.Summary,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageKey,
	)
	return i, err
}

const getMagicRule = `-- name: GetMagicRule :one
SELECT id, project_id, name, description, created_at, updated_at, attributes FROM wiki_magic_rules WHERE id = $1
`

func (q *Queries) GetMagicRule(ctx context.Context, id uuid.UUID) (WikiMagicRule, error) {
	row := q.db.QueryRow(ctx, getMagicRule, id)
	var i WikiMagicRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attributes,
	)
	return i, err
}

const getRelationship = `-- name: GetRelationship :one
SELECT id, project_id, from_entity_id, to_entity_id, type, description, created_at FROM wiki_relationships WHERE id = $1
`

func (q *Queries) GetRelationship(ctx context.Context, id uuid.UUID) (WikiRelationship, error) {
	row := q.db.QueryRow(ctx, getRelationship, id)
	var i WikiRelationship
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromEntityID,
		&i.ToEntityID,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTimelineEvent = `-- name: GetTimelineEvent :one
SELECT id, project_id, entity_id, name, description, era, year, month, day, created_at, updated_at, anchor_event_id, anchor_offset_year, anchor_offset_month, anchor_offset_day FROM wiki_timeline_events WHERE id = $1
`

func (q *Queries) GetTimelineEvent(ctx context.Context, id uuid.UUID) (WikiTimelineEvent, error) {
	row := q.db.QueryRow(ctx, getTimelineEvent, id)
	var i WikiTimelineEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityID,
		&i.Name,
		&i.Description,
		&i.Era,
		&i.Year,
		&i.Month,
		&i.Day,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnchorEventID,
		&i.AnchorOffsetYear,
		&i.AnchorOffsetMonth,
		&i.AnchorOffsetDay,
	)
	return i, err
}

const listEntitiesByParent = `-- name: ListEntitiesByParent :many
SELECT id, project_id, parent_entity_id, type, name, summary, attributes, created_at, updated_at, image_key
FROM wiki_entities
WHERE parent_entity_id = $1
ORDER BY name ASC
`

type ListEntitiesByParentRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	ParentEntityID pgtype.UUID        `json:"parent_entity_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Summary        string             `json:"summary"`
	Attributes     json.RawMessage    `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImageKey       pgtype.Text        `json:"image_key"`
}

func (q *Queries) ListEntitiesByParent(ctx context.Context, parentEntityID pgtype.UUID) ([]ListEntitiesByParentRow, error) {
	rows, err := q.db.Query(ctx, listEntitiesByParent, parentEntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntitiesByParentRow{}
	for rows.Next() {
		var i ListEntitiesByParentRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentEntityID,
			&i.Type,
			&i.Name,
			&i.Summary,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByProject = `-- name: ListEntitiesByProject :many
SELECT id, project_id, parent_entity_id, type, name, summary, attributes, created_at, updated_at, image_key
FROM wiki_entities
WHERE project_id = $1
  AND ($2::text IS NULL OR type = $2::text)
ORDER BY name ASC
`

type ListEntitiesByProjectParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Type      pgtype.Text `json:"type"`
}

type ListEntitiesByProjectRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	ParentEntityID pgtype.UUID        `json:"parent_entity_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Summary        string             `json:"summary"`
	Attributes     json.RawMessage    `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImageKey       pgtype.Text        `json:"image_key"`
}

func (q *Queries) ListEntitiesByProject(ctx context.Context, arg ListEntitiesByProjectParams) ([]ListEntitiesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listEntitiesByProject, arg.ProjectID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntitiesByProjectRow{}
	for rows.Next() {
		var i ListEntitiesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentEntityID,
			&i.Type,
			&i.Name,
			&i.Summary,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMagicRulesByProject = `-- name: ListMagicRulesByProject :many
SELECT id, project_id, name, description, created_at, updated_at, attributes FROM wiki_magic_rules
WHERE project_id = $1
ORDER BY name ASC
`

func (q *Queries) ListMagicRulesByProject(ctx context.Context, projectID uuid.UUID) ([]WikiMagicRule, error) {
	rows, err := q.db.Query(ctx, listMagicRulesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WikiMagicRule{}
	for rows.Next() {
		var i WikiMagicRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMagicRulesForContext = `-- name: ListMagicRulesForContext :many
SELECT id, project_id, name, description, attributes, updated_at
FROM wiki_magic_rules
WHERE project_id = $1
ORDER BY updated_at DESC
LIMIT 5
`

type ListMagicRulesForContextRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Attributes  json.RawMessage    `json:"attributes"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Returns the 5 most recently updated magic rules for AI context injection.
func (q *Queries) ListMagicRulesForContext(ctx context.Context, projectID uuid.UUID) ([]ListMagicRulesForContextRow, error) {
	rows, err := q.db.Query(ctx, listMagicRulesForContext, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMagicRulesForContextRow{}
	for rows.Next() {
		var i ListMagicRulesForContextRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Attributes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionedEntitiesByScene = `-- name: ListMentionedEntitiesByScene :many
SELECT we.id, we.project_id, we.parent_entity_id, we.type, we.name, we.summary,
       we.attributes, we.created_at, we.updated_at, we.image_key
FROM wiki_entities we
JOIN scene_entity_mentions sem ON sem.entity_id = we.id
WHERE sem.scene_id = $1::uuid
  AND sem.branch_name = $2
  AND sem.suppressed = FALSE
ORDER BY we.name ASC
`

type ListMentionedEntitiesBySceneParams struct {
	SceneID    uuid.UUID `json:"scene_id"`
	BranchName string    `json:"branch_name"`
}

type ListMentionedEntitiesBySceneRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	ParentEntityID pgtype.UUID        `json:"parent_entity_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Summary        string             `json:"summary"`
	Attributes     json.RawMessage    `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImageKey       pgtype.Text        `json:"image_key"`
}

func (q *Queries) ListMentionedEntitiesByScene(ctx context.Context, arg ListMentionedEntitiesBySceneParams) ([]ListMentionedEntitiesBySceneRow, error) {
	rows, err := q.db.Query(ctx, listMentionedEntitiesByScene, arg.SceneID, arg.BranchName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMentionedEntitiesBySceneRow{}
	for rows.Next() {
		var i ListMentionedEntitiesBySceneRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentEntityID,
			&i.Type,
			&i.Name,
			&i.Summary,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionsByScene = `-- name: ListMentionsByScene :many
SELECT sem.id, sem.scene_id, sem.entity_id, sem.project_id, sem.branch_name,
       sem.match_text, sem.suppressed, sem.created_at,
       we.name AS entity_name, we.type AS entity_type
FROM scene_entity_mentions sem
JOIN wiki_entities we ON we.id = sem.entity_id
WHERE sem.scene_id = $1 AND sem.branch_name = $2 AND sem.suppressed = FALSE
ORDER BY we.name ASC
`

type ListMentionsBySceneParams struct {
	SceneID    uuid.UUID `json:"scene_id"`
	BranchName string    `json:"branch_name"`
}

type ListMentionsBySceneRow struct {
	ID         uuid.UUID          `json:"id"`
	SceneID    uuid.UUID          `json:"scene_id"`
	EntityID   uuid.UUID          `json:"entity_id"`
	ProjectID  uuid.UUID          `json:"project_id"`
	BranchName string             `json:"branch_name"`
	MatchText  string             `json:"match_text"`
	Suppressed bool               `json:"suppressed"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	EntityName string             `json:"entity_name"`
	EntityType string             `json:"entity_type"`
}

func (q *Queries) ListMentionsByScene(ctx context.Context, arg ListMentionsBySceneParams) ([]ListMentionsBySceneRow, error) {
	rows, err := q.db.Query(ctx, listMentionsByScene, arg.SceneID, arg.BranchName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMentionsBySceneRow{}
	for rows.Next() {
		var i ListMentionsBySceneRow
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.EntityID,
			&i.ProjectID,
			&i.BranchName,
			&i.MatchText,
			&i.Suppressed,
			&i.CreatedAt,
			&i.EntityName,
			&i.EntityType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsByProject = `-- name: ListRelationshipsByProject :many
SELECT id, project_id, from_entity_id, to_entity_id, type, description, created_at FROM wiki_relationships
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRelationshipsByProject(ctx context.Context, projectID uuid.UUID) ([]WikiRelationship, error) {
	rows, err := q.db.Query(ctx, listRelationshipsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WikiRelationship{}
	for rows.Next() {
		var i WikiRelationship
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromEntityID,
			&i.ToEntityID,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenesByEntity = `-- name: ListScenesByEntity :many
SELECT
    s.id         AS scene_id,
    s.title      AS scene_title,
    s.sort_order AS scene_order,
    c.id         AS chapter_id,
    c.title      AS chapter_title,
    c.sort_order AS chapter_order,
    sem.branch_name
FROM scenes s
JOIN scene_entity_mentions sem ON sem.scene_id = s.id
JOIN chapters c ON c.id = s.chapter_id
WHERE sem.entity_id = $1 AND sem.branch_name = $2 AND sem.suppressed = FALSE
ORDER BY c.sort_order, s.sort_order
`

type ListScenesByEntityParams struct {
	EntityID   uuid.UUID `json:"entity_id"`
	BranchName string    `json:"branch_name"`
}

type ListScenesByEntityRow struct {
	SceneID      uuid.UUID `json:"scene_id"`
	SceneTitle   string    `json:"scene_title"`
	SceneOrder   int32     `json:"scene_order"`
	ChapterID    uuid.UUID `json:"chapter_id"`
	ChapterTitle string    `json:"chapter_title"`
	ChapterOrder int32     `json:"chapter_order"`
	BranchName   string    `json:"branch_name"`
}

func (q *Queries) ListScenesByEntity(ctx context.Context, arg ListScenesByEntityParams) ([]ListScenesByEntityRow, error) {
	rows, err := q.db.Query(ctx, listScenesByEntity, arg.EntityID, arg.BranchName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScenesByEntityRow{}
	for rows.Next() {
		var i ListScenesByEntityRow
		if err := rows.Scan(
			&i.SceneID,
			&i.SceneTitle,
			&i.SceneOrder,
			&i.ChapterID,
			&i.ChapterTitle,
			&i.ChapterOrder,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenesByEntityForProject = `-- name: ListScenesByEntityForProject :many
SELECT
    s.id            AS scene_id,
    s.title         AS scene_title,
    s.sort_order    AS scene_order,
    c.id            AS chapter_id,
    c.title         AS chapter_title,
    c.sort_order    AS chapter_order,
    p.git_repo_path,
    sem.match_text,
    sem.branch_name
FROM scenes s
JOIN scene_entity_mentions sem ON sem.scene_id = s.id
JOIN chapters c ON c.id = s.chapter_id
JOIN acts a ON a.id = c.act_id
JOIN projects p ON p.id = a.project_id
WHERE sem.entity_id = $1
  AND sem.suppressed = FALSE
ORDER BY c.sort_order, s.sort_order
`

type ListScenesByEntityForProjectRow struct {
	SceneID      uuid.UUID `json:"scene_id"`
	SceneTitle   string    `json:"scene_title"`
	SceneOrder   int32     `json:"scene_order"`
	ChapterID    uuid.UUID `json:"chapter_id"`
	ChapterTitle string    `json:"chapter_title"`
	ChapterOrder int32     `json:"chapter_order"`
	GitRepoPath  string    `json:"git_repo_path"`
	MatchText    string    `json:"match_text"`
	BranchName   string    `json:"branch_name"`
}

// All non-suppressed scenes that mention an entity, with chapter/project context.
// Used by rename-cascade preview to know which scenes to patch.
func (q *Queries) ListScenesByEntityForProject(ctx context.Context, entityID uuid.UUID) ([]ListScenesByEntityForProjectRow, error) {
	rows, err := q.db.Query(ctx, listScenesByEntityForProject, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScenesByEntityForProjectRow{}
	for rows.Next() {
		var i ListScenesByEntityForProjectRow
		if err := rows.Scan(
			&i.SceneID,
			&i.SceneTitle,
			&i.SceneOrder,
			&i.ChapterID,
			&i.ChapterTitle,
			&i.ChapterOrder,
			&i.GitRepoPath,
			&i.MatchText,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineEventsByProject = `-- name: ListTimelineEventsByProject :many
SELECT id, project_id, entity_id, name, description, era, year, month, day, created_at, updated_at, anchor_event_id, anchor_offset_year, anchor_offset_month, anchor_offset_day FROM wiki_timeline_events
WHERE project_id = $1
ORDER BY year NULLS LAST, month NULLS LAST, day NULLS LAST, name ASC
`

func (q *Queries) ListTimelineEventsByProject(ctx context.Context, projectID uuid.UUID) ([]WikiTimelineEvent, error) {
	rows, err := q.db.Query(ctx, listTimelineEventsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WikiTimelineEvent{}
	for rows.Next() {
		var i WikiTimelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityID,
			&i.Name,
			&i.Description,
			&i.Era,
			&i.Year,
			&i.Month,
			&i.Day,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnchorEventID,
			&i.AnchorOffsetYear,
			&i.AnchorOffsetMonth,
			&i.AnchorOffsetDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suppressAllMentions = `-- name: SuppressAllMentions :exec
UPDATE scene_entity_mentions SET suppressed = TRUE
WHERE scene_id = $1 AND branch_name = $2
`

type SuppressAllMentionsParams struct {
	SceneID    uuid.UUID `json:"scene_id"`
	BranchName string    `json:"branch_name"`
}

func (q *Queries) SuppressAllMentions(ctx context.Context, arg SuppressAllMentionsParams) error {
	_, err := q.db.Exec(ctx, suppressAllMentions, arg.SceneID, arg.BranchName)
	return err
}

const suppressMention = `-- name: SuppressMention :exec
UPDATE scene_entity_mentions SET suppressed = TRUE WHERE id = $1
`

func (q *Queries) SuppressMention(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, suppressMention, id)
	return err
}

const updateEntity = `-- name: UpdateEntity :one
UPDATE wiki_entities
SET name       = COALESCE($2, name),
    summary    = COALESCE($3, summary),
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, parent_entity_id, type, name, summary, attributes, created_at, updated_at, image_key
`

type UpdateEntityParams struct {
	ID      uuid.UUID   `json:"id"`
	Name    pgtype.Text `json:"name"`
	Summary pgtype.Text `json:"summary"`
}

type UpdateEntityRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	ParentEntityID pgtype.UUID        `json:"parent_entity_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Summary        string             `json:"summary"`
	Attributes     json.RawMessage    `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImageKey       pgtype.Text        `json:"image_key"`
}

func (q *Queries) UpdateEntity(ctx context.Context, arg UpdateEntityParams) (UpdateEntityRow, error) {
	row := q.db.QueryRow(ctx, updateEntity, arg.ID, arg.Name, arg.Summary)
	var i UpdateEntityRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentEntityID,
		&i.Type,
		&i.Name,
		&i.Summary,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageKey,
	)
	return i, err
}

const updateEntityAttributes = `-- name: UpdateEntityAttributes :one
UPDATE wiki_entities
SET attributes = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, parent_entity_id, type, name, summary, attributes, created_at, updated_at, image_key
`

type UpdateEntityAttributesParams struct {
	ID         uuid.UUID       `json:"id"`
	Attributes json.RawMessage `json:"attributes"`
}

type UpdateEntityAttributesRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	ParentEntityID pgtype.UUID        `json:"parent_entity_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Summary        string             `json:"summary"`
	Attributes     json.RawMessage    `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImageKey       pgtype.Text        `json:"image_key"`
}

func (q *Queries) UpdateEntityAttributes(ctx context.Context, arg UpdateEntityAttributesParams) (UpdateEntityAttributesRow, error) {
	row := q.db.QueryRow(ctx, updateEntityAttributes, arg.ID, arg.Attributes)
	var i UpdateEntityAttributesRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentEntityID,
		&i.Type,
		&i.Name,
		&i.Summary,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageKey,
	)
	return i, err
}

const updateEntityImage = `-- name: UpdateEntityImage :one
UPDATE wiki_entities
SET image_key  = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, parent_entity_id, type, name, summary, attributes, created_at, updated_at, image_key
`

type UpdateEntityImageParams struct {
	ID       uuid.UUID   `json:"id"`
	ImageKey pgtype.Text `json:"image_key"`
}

type UpdateEntityImageRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	ParentEntityID pgtype.UUID        `json:"parent_entity_id"`
	Type           string             `json:"type"`
	Name           string             `json:"name"`
	Summary        string             `json:"summary"`
	Attributes     json.RawMessage    `json:"attributes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ImageKey       pgtype.Text        `json:"image_key"`
}

func (q *Queries) UpdateEntityImage(ctx context.Context, arg UpdateEntityImageParams) (UpdateEntityImageRow, error) {
	row := q.db.QueryRow(ctx, updateEntityImage, arg.ID, arg.ImageKey)
	var i UpdateEntityImageRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentEntityID,
		&i.Type,
		&i.Name,
		&i.Summary,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageKey,
	)
	return i, err
}

const updateMagicRule = `-- name: UpdateMagicRule :one
UPDATE wiki_magic_rules
SET name        = COALESCE($2, name),
    description = COALESCE($3, description),
    attributes  = COALESCE($4, attributes),
    updated_at  = now()
WHERE id = $1
RETURNING id, project_id, name, description, created_at, updated_at, attributes
`

type UpdateMagicRuleParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Attributes  []byte      `json:"attributes"`
}

func (q *Queries) UpdateMagicRule(ctx context.Context, arg UpdateMagicRuleParams) (WikiMagicRule, error) {
	row := q.db.QueryRow(ctx, updateMagicRule,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Attributes,
	)
	var i WikiMagicRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attributes,
	)
	return i, err
}

const updateMentionMatchText = `-- name: UpdateMentionMatchText :exec
UPDATE scene_entity_mentions
SET match_text = $2
WHERE scene_id = $3 AND entity_id = $1
`

type UpdateMentionMatchTextParams struct {
	EntityID  uuid.UUID `json:"entity_id"`
	MatchText string    `json:"match_text"`
	SceneID   uuid.UUID `json:"scene_id"`
}

func (q *Queries) UpdateMentionMatchText(ctx context.Context, arg UpdateMentionMatchTextParams) error {
	_, err := q.db.Exec(ctx, updateMentionMatchText, arg.EntityID, arg.MatchText, arg.SceneID)
	return err
}

const updateTimelineEvent = `-- name: UpdateTimelineEvent :one
UPDATE wiki_timeline_events
SET name                = COALESCE($2, name),
    description         = COALESCE($3, description),
    era                 = COALESCE($4, era),
    year                = COALESCE($5, year),
    month               = COALESCE($6, month),
    day                 = COALESCE($7, day),
    anchor_event_id     = COALESCE($8, anchor_event_id),
    anchor_offset_year  = COALESCE($9, anchor_offset_year),
    anchor_offset_month = COALESCE($10, anchor_offset_month),
    anchor_offset_day   = COALESCE($11, anchor_offset_day),
    updated_at          = now()
WHERE id = $1
RETURNING id, project_id, entity_id, name, description, era, year, month, day, created_at, updated_at, anchor_event_id, anchor_offset_year, anchor_offset_month, anchor_offset_day
`

type UpdateTimelineEventParams struct {
	ID                uuid.UUID   `json:"id"`
	Name              pgtype.Text `json:"name"`
	Description       pgtype.Text `json:"description"`
	Era               pgtype.Text `json:"era"`
	Year              pgtype.Int4 `json:"year"`
	Month             pgtype.Int4 `json:"month"`
	Day               pgtype.Int4 `json:"day"`
	AnchorEventID     pgtype.UUID `json:"anchor_event_id"`
	AnchorOffsetYear  pgtype.Int4 `json:"anchor_offset_year"`
	AnchorOffsetMonth pgtype.Int4 `json:"anchor_offset_month"`
	AnchorOffsetDay   pgtype.Int4 `json:"anchor_offset_day"`
}

func (q *Queries) UpdateTimelineEvent(ctx context.Context, arg UpdateTimelineEventParams) (WikiTimelineEvent, error) {
	row := q.db.QueryRow(ctx, updateTimelineEvent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Era,
		arg.Year,
		arg.Month,
		arg.Day,
		arg.AnchorEventID,
		arg.AnchorOffsetYear,
		arg.AnchorOffsetMonth,
		arg.AnchorOffsetDay,
	)
	var i WikiTimelineEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityID,
		&i.Name,
		&i.Description,
		&i.Era,
		&i.Year,
		&i.Month,
		&i.Day,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnchorEventID,
		&i.AnchorOffsetYear,
		&i.AnchorOffsetMonth,
		&i.AnchorOffsetDay,
	)
	return i, err
}

const upsertSceneEntityMention = `-- name: UpsertSceneEntityMention :one
INSERT INTO scene_entity_mentions (scene_id, entity_id, project_id, branch_name, match_text)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scene_id, entity_id, branch_name)
DO UPDATE SET match_text = EXCLUDED.match_text, suppressed = FALSE
RETURNING id, scene_id, entity_id, project_id, branch_name, match_text, suppressed, created_at
`

type UpsertSceneEntityMentionParams struct {
	SceneID    uuid.UUID `json:"scene_id"`
	EntityID   uuid.UUID `json:"entity_id"`
	ProjectID  uuid.UUID `json:"project_id"`
	BranchName string    `json:"branch_name"`
	MatchText  string    `json:"match_text"`
}

func (q *Queries) UpsertSceneEntityMention(ctx context.Context, arg UpsertSceneEntityMentionParams) (SceneEntityMention, error) {
	row := q.db.QueryRow(ctx, upsertSceneEntityMention,
		arg.SceneID,
		arg.EntityID,
		arg.ProjectID,
		arg.BranchName,
		arg.MatchText,
	)
	var i SceneEntityMention
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.EntityID,
		&i.ProjectID,
		&i.BranchName,
		&i.MatchText,
		&i.Suppressed,
		&i.CreatedAt,
	)
	return i, err
}
