// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workshop.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createWorkshopSession = `-- name: CreateWorkshopSession :one
INSERT INTO workshop_sessions (project_id, user_id, title)
VALUES ($1, $2, $3)
RETURNING id, project_id, user_id, title, messages, created_at, updated_at
`

type CreateWorkshopSessionParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
}

func (q *Queries) CreateWorkshopSession(ctx context.Context, arg CreateWorkshopSessionParams) (WorkshopSession, error) {
	row := q.db.QueryRow(ctx, createWorkshopSession, arg.ProjectID, arg.UserID, arg.Title)
	var i WorkshopSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Messages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkshopSession = `-- name: DeleteWorkshopSession :exec
DELETE FROM workshop_sessions
WHERE  id         = $1
  AND  project_id = $2
  AND  user_id    = $3
`

type DeleteWorkshopSessionParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWorkshopSession(ctx context.Context, arg DeleteWorkshopSessionParams) error {
	_, err := q.db.Exec(ctx, deleteWorkshopSession, arg.ID, arg.ProjectID, arg.UserID)
	return err
}

const getWorkshopSession = `-- name: GetWorkshopSession :one
SELECT id, project_id, user_id, title, messages, created_at, updated_at
FROM   workshop_sessions
WHERE  id         = $1
  AND  project_id = $2
  AND  user_id    = $3
`

type GetWorkshopSessionParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkshopSession(ctx context.Context, arg GetWorkshopSessionParams) (WorkshopSession, error) {
	row := q.db.QueryRow(ctx, getWorkshopSession, arg.ID, arg.ProjectID, arg.UserID)
	var i WorkshopSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Messages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkshopSessions = `-- name: ListWorkshopSessions :many

SELECT id, project_id, user_id, title, messages, created_at, updated_at
FROM   workshop_sessions
WHERE  project_id = $1
  AND  user_id    = $2
ORDER  BY updated_at DESC
`

type ListWorkshopSessionsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

// ============================
// Workshop Sessions (C2)
// ============================
// Named, persistent AI chat sessions per project and user.
// Messages are stored as a JSONB array; each element is:
//
//	{ "role": "user"|"assistant", "content": "...", "timestamp": "ISO-8601" }
func (q *Queries) ListWorkshopSessions(ctx context.Context, arg ListWorkshopSessionsParams) ([]WorkshopSession, error) {
	rows, err := q.db.Query(ctx, listWorkshopSessions, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkshopSession{}
	for rows.Next() {
		var i WorkshopSession
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Title,
			&i.Messages,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkshopSession = `-- name: UpdateWorkshopSession :one
UPDATE workshop_sessions
SET title      = $4,
    messages   = $5,
    updated_at = NOW()
WHERE  id         = $1
  AND  project_id = $2
  AND  user_id    = $3
RETURNING id, project_id, user_id, title, messages, created_at, updated_at
`

type UpdateWorkshopSessionParams struct {
	ID        uuid.UUID       `json:"id"`
	ProjectID uuid.UUID       `json:"project_id"`
	UserID    uuid.UUID       `json:"user_id"`
	Title     string          `json:"title"`
	Messages  json.RawMessage `json:"messages"`
}

func (q *Queries) UpdateWorkshopSession(ctx context.Context, arg UpdateWorkshopSessionParams) (WorkshopSession, error) {
	row := q.db.QueryRow(ctx, updateWorkshopSession,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Title,
		arg.Messages,
	)
	var i WorkshopSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Messages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
